#!/usr/bin/env node
/**
 * Writes src/time-zones.ts: which of Waypoint's countries each IANA time zone belongs to.
 *
 *   node packages/content/scripts/time-zones.mjs [/usr/share/zoneinfo]
 *
 * Reads the tz database's zone.tab (one country per zone name) and tzdata.zi (the links,
 * including old names such as Asia/Calcutta that browsers still report). A link takes the
 * country of its target only when zone.tab doesn't list it itself, so zones merged across
 * borders (Africa/Dar_es_Salaam → Africa/Nairobi) keep their own country.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const zoneinfo = process.argv[2] ?? '/usr/share/zoneinfo';
const countriesSource = readFileSync(join(here, '../src/countries.ts'), 'utf8');
const supported = new Set([...countriesSource.matchAll(/code: '([A-Z]{2})'/g)].map((m) => m[1]));

const listed = new Map();
for (const line of readFileSync(join(zoneinfo, 'zone.tab'), 'utf8').split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [country, , zone] = line.split('\t');
  listed.set(zone, country);
}
const version =
  readFileSync(join(zoneinfo, 'tzdata.zi'), 'utf8').match(/^# version (\S+)/m)?.[1] ?? '?';

const map = new Map();
for (const [zone, country] of listed) if (supported.has(country)) map.set(zone, country);
for (const line of readFileSync(join(zoneinfo, 'tzdata.zi'), 'utf8').split('\n')) {
  const m = line.match(/^L (\S+) (\S+)$/);
  if (!m) continue;
  const [, target, link] = m;
  if (listed.has(link)) continue;
  const country = map.get(target);
  if (country) map.set(link, country);
}

const missing = [...supported].filter((c) => ![...map.values()].includes(c));
if (missing.length) throw new Error(`No time zone found for ${missing.join(', ')}`);

const entries = [...map.entries()].sort(([a], [b]) => (a < b ? -1 : 1));
const body = entries.map(([zone, country]) => `  '${zone}': '${country}',`).join('\n');
writeFileSync(
  join(here, '../src/time-zones.ts'),
  `/**
 * Which of Waypoint's countries each IANA time zone belongs to, from the tz database
 * (${version}): zone.tab, plus the links browsers still report (such as Asia/Calcutta).
 * Generated by scripts/time-zones.mjs — do not edit by hand.
 */
export const TIME_ZONE_COUNTRY: Readonly<Record<string, string>> = {
${body}
};
`,
);
console.log(`${entries.length} time zones for ${supported.size} countries (tz ${version})`);
