/**
 * Makes every Waypoint logo file from one drawing (apps/web/src/components/brand/geometry.ts):
 *
 *   pnpm brand            # from the repository root
 *
 * 1. The wordmark: "Waypoint" set in Overpass SemiBold, turned into a path and kerned by hand
 *    (apps/web/src/components/brand/wordmark.ts, read by the React logo).
 * 2. The master SVGs in apps/web/public/brand and the favicon, apps/web/src/app/icon.svg.
 * 3. Every PNG icon of the website and the phone app, drawn by Chromium at its exact size
 *    (the browser the web app's browser tests use; nothing is downloaded).
 *
 * Run it again after changing the geometry; commit what it writes.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  BRAND_HEX,
  GLYPH_BOX,
  glyphSvg,
  MARK_GRID,
  TILE_RADIUS,
} from '../../apps/web/src/components/brand/geometry.ts';
import { launch, ROOT, rasterise, sharp } from './browser.mjs';
import { readFont } from './ttf.mjs';

const WEB = join(ROOT, 'apps', 'web');
const MOBILE = join(ROOT, 'apps', 'mobile');
const FONT = join(
  ROOT,
  'node_modules/.pnpm/@expo-google-fonts+overpass@0.4.2/node_modules/@expo-google-fonts/overpass/600SemiBold/Overpass_600SemiBold.ttf',
);

// ---------------------------------------------------------------------------------------------
// 1. The wordmark
// ---------------------------------------------------------------------------------------------

/** Cap height of the wordmark on the mark's grid: half the tile, so the two sit as one line. */
const CAP = 30;
/** Overpass's cap height in font units (the top of the W). */
const FONT_CAP = 1400;
/** Space between letters, in font units: a touch tighter than the text face, as a name is. */
const TRACKING = -12;
/** Hand kerning, in font units, for the pairs that need it at this size. */
const KERN: Record<string, number> = { Wa: -70, ay: -10, yp: 10, oi: 0, in: 0, nt: -10 };

const font = readFont(FONT);
const scale = CAP / FONT_CAP;
const word = 'Waypoint';
const contours: string[] = [];
let pen = 0;
for (let i = 0; i < word.length; i++) {
  const ch = word[i] as string;
  const glyph = font.glyph(ch, { dx: pen * scale, dy: 0, scale });
  contours.push(...glyph.contours);
  const next = word[i + 1];
  pen += glyph.advance + TRACKING + (next ? (KERN[ch + next] ?? 0) : 0);
}
const wordWidth = Math.round((pen - TRACKING) * scale * 100) / 100;
const wordPath = contours.join('');
/** The descender of p and y reaches this far below the baseline (font units 2000/em). */
const DESCENT = Math.ceil((470 * scale + 1) * 10) / 10;

writeFileSync(
  join(WEB, 'src/components/brand/wordmark.ts'),
  `/**
 * "Waypoint" in Overpass SemiBold as one path, kerned by hand. Generated by
 * scripts/brand/build.mts (\`pnpm brand\`): do not edit by hand.
 *
 * Units are those of the mark's 64-unit grid: the baseline is at y = 0 and capitals reach
 * y = -${CAP}; the descenders of p and y go down to y = ${DESCENT}.
 */
export const WORDMARK = {
  d: '${wordPath}',
  width: ${wordWidth},
  cap: ${CAP},
  descent: ${DESCENT},
} as const;
`,
);

// ---------------------------------------------------------------------------------------------
// 2. Master SVGs
// ---------------------------------------------------------------------------------------------

const S = BRAND_HEX;

/** The glyph scaled by `k` about the centre of its own ink, then centred on the grid. */
function centredGlyph(fill: string, k: number): string {
  const cx = GLYPH_BOX.x + GLYPH_BOX.width / 2;
  const cy = GLYPH_BOX.y + GLYPH_BOX.height / 2;
  const half = MARK_GRID / 2;
  return `<g transform="translate(${half} ${half}) scale(${k}) translate(${-cx} ${-cy})">${glyphSvg(fill)}</g>`;
}

/** The mark: glyph on the rounded slate tile. `adaptive` lightens the tile in a dark UI. */
function markSvg({ adaptive = false, title = true } = {}): string {
  const style = adaptive
    ? `<style>.tile{fill:${S.slate}}@media (prefers-color-scheme:dark){.tile{fill:${S.slateOnDark}}}</style>`
    : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MARK_GRID} ${MARK_GRID}" width="${MARK_GRID}" height="${MARK_GRID}">${title ? '<title>Waypoint</title>' : ''}${style}<rect class="tile" width="${MARK_GRID}" height="${MARK_GRID}" rx="${TILE_RADIUS}" fill="${S.slate}"/>${glyphSvg(S.signal)}</svg>`;
}

/** The glyph alone in one colour (`currentColor` when placed inline). */
function monoSvg(fill = 'currentColor'): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MARK_GRID} ${MARK_GRID}" width="${MARK_GRID}" height="${MARK_GRID}" fill="${fill}"><title>Waypoint</title>${glyphSvg(fill)}</svg>`;
}

/** Mark and wordmark side by side; the word follows the colour scheme of whatever shows it. */
const GAP = 14;
function lockupSvg(): string {
  const width = Math.ceil(MARK_GRID + GAP + wordWidth);
  const baseline = MARK_GRID / 2 + CAP / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${MARK_GRID}" width="${width * 2}" height="${MARK_GRID * 2}"><title>Waypoint</title><style>.word{fill:${S.slate}}@media (prefers-color-scheme:dark){.word{fill:${S.paper}}}</style><rect width="${MARK_GRID}" height="${MARK_GRID}" rx="${TILE_RADIUS}" fill="${S.slate}"/>${glyphSvg(S.signal)}<path class="word" transform="translate(${MARK_GRID + GAP} ${baseline})" d="${wordPath}"/></svg>`;
}

const brand = join(WEB, 'public', 'brand');
writeFileSync(join(brand, 'waypoint-mark.svg'), `${markSvg()}\n`);
writeFileSync(join(brand, 'waypoint-mark-mono.svg'), `${monoSvg()}\n`);
writeFileSync(join(brand, 'waypoint-lockup.svg'), `${lockupSvg()}\n`);
writeFileSync(join(WEB, 'src/app/icon.svg'), `${markSvg({ adaptive: true })}\n`);

// ---------------------------------------------------------------------------------------------
// 3. PNG icons
// ---------------------------------------------------------------------------------------------

/** A square picture of `px` pixels with the glyph at `k` times its size on the tile grid. */
function square(px: number, inner: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MARK_GRID} ${MARK_GRID}" width="${px}" height="${px}">${inner}</svg>`;
}
const tile = `<rect width="${MARK_GRID}" height="${MARK_GRID}" rx="${TILE_RADIUS}" fill="${S.slate}"/>`;
const fullBleed = `<rect width="${MARK_GRID}" height="${MARK_GRID}" fill="${S.slate}"/>`;

/**
 * How large the glyph may be where the platform crops the icon to a shape it chooses: the
 * glyph's ink must fit inside a circle of `safe` (a fraction of the icon's width).
 */
function fitIn(safe: number): number {
  const radius = Math.hypot(GLYPH_BOX.width, GLYPH_BOX.height) / 2;
  return ((safe / 2) * MARK_GRID) / radius;
}

type Icon = { file: string; px: number; svg: string; opaque?: boolean };
const glyph = (k: number, fill = S.signal) => centredGlyph(fill, k);
const ICONS: Icon[] = [
  // The website: rounded tile where the browser shows the picture as it is.
  { file: join(WEB, 'public/icons/favicon-32.png'), px: 32, svg: square(32, tile + glyph(1)) },
  { file: join(WEB, 'public/icons/icon-192.png'), px: 192, svg: square(192, tile + glyph(1)) },
  { file: join(WEB, 'public/icons/icon-512.png'), px: 512, svg: square(512, tile + glyph(1)) },
  // Android crops a maskable icon to its own shape: the glyph stays inside the middle 80%.
  {
    file: join(WEB, 'public/icons/maskable-512.png'),
    px: 512,
    svg: square(512, fullBleed + glyph(fitIn(0.72))),
  },
  // iOS rounds the corners itself and wants no transparency.
  {
    file: join(WEB, 'public/icons/apple-icon-180.png'),
    px: 180,
    svg: square(180, fullBleed + glyph(0.92)),
    opaque: true,
  },
  {
    file: join(WEB, 'src/app/apple-icon.png'),
    px: 180,
    svg: square(180, fullBleed + glyph(0.92)),
    opaque: true,
  },
  // The phone app. iOS: full square, no transparency.
  {
    file: join(MOBILE, 'assets/icon.png'),
    px: 1024,
    svg: square(1024, fullBleed + glyph(0.92)),
    opaque: true,
  },
  // Android's adaptive icon: the foreground on its own (the slate is app.config's
  // backgroundColor); the launcher may crop to the middle 61%, so the glyph keeps inside it.
  {
    file: join(MOBILE, 'assets/adaptive-icon.png'),
    px: 1024,
    svg: square(1024, glyph(fitIn(0.58))),
  },
  // Android 13's themed icon: the same shape in one colour, which the launcher tints.
  {
    file: join(MOBILE, 'assets/monochrome-icon.png'),
    px: 1024,
    svg: square(1024, glyph(fitIn(0.58), '#ffffff')),
  },
  // The splash screen shows this at 160 points on the slate background.
  {
    file: join(MOBILE, 'assets/splash-icon.png'),
    px: 1024,
    svg: square(1024, glyph(1.25)),
  },
  { file: join(MOBILE, 'assets/favicon.png'), px: 48, svg: square(48, tile + glyph(1)) },
];

const browser = await launch();
const toImage = sharp();
try {
  for (const icon of ICONS) {
    const png = await rasterise(browser, icon.svg, icon.px, icon.opaque ? S.slate : undefined);
    let image = toImage(png);
    if (icon.opaque) image = image.removeAlpha();
    await image.png({ compressionLevel: 9, adaptiveFiltering: true }).toFile(icon.file);
    console.log(`${icon.px}px  ${icon.file.slice(ROOT.length + 1)}`);
  }
} finally {
  await browser.close();
}
