import type { LearningResource } from './types';

/**
 * Learning resources, free first. Checked on 2026-09-29 (URL, provider, cost model).
 * `languages` lists what we confirmed or what the provider is known for; always check a course
 * page for your language. Paid options are included only where no strong free option exists.
 */
const CHECKED = '2026-09-29';

export const LEARNING_RESOURCES: LearningResource[] = [
  // Foundations & digital
  {
    id: 'learnfree',
    title: 'LearnFree (GCF) computer, internet and job skills',
    provider: 'GCF LearnFree',
    url: 'https://www.learnfree.org/',
    skills: [
      'digital-basics',
      'online-safety',
      'office-docs',
      'spreadsheets',
      'online-collaboration',
      'literacy-numeracy',
      'personal-finance',
    ],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'khan-academy',
    title: 'Khan Academy',
    provider: 'Khan Academy',
    url: 'https://www.khanacademy.org/',
    skills: ['literacy-numeracy', 'statistics-basics', 'personal-finance', 'programming-basics'],
    cost: 'free',
    languages: ['en', 'es', 'pt', 'fr', 'hi'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'learning-how-to-learn',
    title: 'Learning How to Learn',
    provider: 'Deep Teaching Solutions (Coursera)',
    url: 'https://www.coursera.org/learn/learning-how-to-learn',
    skills: ['learning-to-learn'],
    cost: 'free-audit',
    hours: 15,
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'excel-video-training',
    title: 'Excel video training',
    provider: 'Microsoft Support',
    url: 'https://support.microsoft.com/en-us/office/excel-video-training-9bc05390-e94c-46af-a5b3-d7c22f6990bb',
    skills: ['spreadsheets'],
    cost: 'free',
    languages: ['en'],
    format: 'video',
    checkedAt: CHECKED,
  },
  {
    id: 'openlearn',
    title: 'OpenLearn free courses',
    provider: 'The Open University',
    url: 'https://www.open.edu/openlearn/',
    skills: [
      'writing-clearly',
      'personal-finance',
      'entrepreneurship',
      'learning-to-learn',
      'climate-literacy',
    ],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'alison',
    title: 'Alison free certificate courses',
    provider: 'Alison',
    url: 'https://alison.com/',
    skills: ['customer-service', 'caregiving', 'hr-basics', 'project-coordination', 'food-safety'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // Data
  {
    id: 'kaggle-learn',
    title: 'Kaggle Learn micro-courses',
    provider: 'Kaggle',
    url: 'https://www.kaggle.com/learn',
    skills: [
      'data-analysis',
      'sql',
      'data-visualisation',
      'programming-basics',
      'ml-basics',
      'data-cleaning',
    ],
    cost: 'free',
    languages: ['en'],
    format: 'practice',
    checkedAt: CHECKED,
  },
  {
    id: 'mit-ocw',
    title: 'MIT OpenCourseWare',
    provider: 'MIT',
    url: 'https://ocw.mit.edu/',
    skills: ['statistics-basics', 'programming-basics', 'financial-analysis', 'ml-basics'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // AI
  {
    id: 'elements-of-ai',
    title: 'Elements of AI',
    provider: 'University of Helsinki & MinnaLearn',
    url: 'https://www.elementsofai.com/',
    skills: ['ai-literacy', 'ml-basics'],
    cost: 'free',
    languages: ['en', 'fr', 'de', 'es', 'pt', 'it', 'nl', 'pl', 'sv', 'uk'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'ai-for-everyone',
    title: 'AI For Everyone',
    provider: 'DeepLearning.AI (Coursera)',
    url: 'https://www.coursera.org/learn/ai-for-everyone',
    skills: ['ai-literacy'],
    cost: 'free-audit',
    hours: 7,
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'anthropic-academy',
    title: 'Anthropic Academy (Claude 101 and more)',
    provider: 'Anthropic',
    url: 'https://anthropic.skilljar.com/',
    skills: ['prompting', 'ai-literacy', 'ai-automation'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'deeplearning-ai-short-courses',
    title: 'DeepLearning.AI short courses',
    provider: 'DeepLearning.AI',
    url: 'https://www.deeplearning.ai/short-courses/',
    skills: ['prompting', 'ai-automation', 'ai-evaluation'],
    cost: 'free-audit',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'ibm-skillsbuild',
    title: 'IBM SkillsBuild',
    provider: 'IBM',
    url: 'https://skillsbuild.org/',
    skills: ['ai-literacy', 'cybersecurity-basics', 'data-analysis', 'cloud-basics', 'it-support'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'microsoft-learn',
    title: 'Microsoft Learn training',
    provider: 'Microsoft',
    url: 'https://learn.microsoft.com/en-us/training/',
    skills: [
      'cloud-basics',
      'ai-literacy',
      'cybersecurity-basics',
      'office-docs',
      'data-visualisation',
    ],
    cost: 'free',
    languages: ['en', 'es', 'fr', 'pt', 'ar'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // Software & IT
  {
    id: 'freecodecamp',
    title: 'freeCodeCamp curriculum',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn',
    skills: ['web-development', 'programming-basics', 'data-analysis', 'version-control'],
    cost: 'free',
    languages: ['en', 'es', 'pt', 'zh', 'it', 'uk', 'ja', 'de'],
    format: 'practice',
    checkedAt: CHECKED,
  },
  {
    id: 'cs50x',
    title: 'CS50x: Introduction to Computer Science',
    provider: 'Harvard University',
    url: 'https://cs50.harvard.edu/x/',
    skills: ['programming-basics', 'problem-solving', 'web-development'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'the-odin-project',
    title: 'The Odin Project',
    provider: 'The Odin Project',
    url: 'https://www.theodinproject.com/',
    skills: ['web-development', 'version-control'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'w3schools',
    title: 'W3Schools tutorials',
    provider: 'W3Schools',
    url: 'https://www.w3schools.com/',
    skills: ['web-development', 'sql'],
    cost: 'free',
    languages: ['en'],
    format: 'practice',
    checkedAt: CHECKED,
  },
  {
    id: 'cisco-netacad',
    title: 'Cisco Networking Academy introductory courses',
    provider: 'Cisco',
    url: 'https://www.netacad.com/',
    skills: ['networking-basics', 'cybersecurity-basics', 'it-support'],
    cost: 'free',
    languages: ['en', 'es', 'fr', 'pt', 'ar'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'google-it-support',
    title: 'Google IT Support Professional Certificate',
    provider: 'Google (Coursera)',
    url: 'https://www.coursera.org/professional-certificates/google-it-support',
    skills: ['it-support', 'networking-basics', 'cybersecurity-basics'],
    cost: 'paid',
    languages: ['en', 'es', 'pt'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // Business, marketing & creative
  {
    id: 'hubspot-academy',
    title: 'HubSpot Academy',
    provider: 'HubSpot',
    url: 'https://academy.hubspot.com/',
    skills: ['social-media-marketing', 'sales', 'web-content', 'copywriting'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'canva-design-school',
    title: 'Canva Design School',
    provider: 'Canva',
    url: 'https://www.canva.com/designschool/',
    skills: ['graphic-design', 'social-media-marketing', 'video-editing'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // Money
  {
    id: 'moneyhelper',
    title: 'MoneyHelper guides and tools',
    provider: 'Money and Pensions Service (UK)',
    url: 'https://www.moneyhelper.org.uk/en',
    skills: ['personal-finance'],
    cost: 'free',
    languages: ['en', 'cy'],
    format: 'guide',
    regions: ['GB'],
    checkedAt: CHECKED,
  },
  {
    id: 'cfpb-consumer-tools',
    title: 'CFPB consumer tools',
    provider: 'Consumer Financial Protection Bureau (US)',
    url: 'https://www.consumerfinance.gov/consumer-tools/',
    skills: ['personal-finance'],
    cost: 'free',
    languages: ['en', 'es'],
    format: 'guide',
    regions: ['US'],
    checkedAt: CHECKED,
  },

  // Health, care & safety
  {
    id: 'openwho',
    title: 'OpenWHO courses',
    provider: 'World Health Organization',
    url: 'https://openwho.org/',
    skills: ['community-health', 'psychological-first-aid', 'caregiving'],
    cost: 'free',
    languages: ['en', 'fr', 'es', 'ar', 'pt', 'ru', 'zh', 'sw', 'hi'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'red-cross-first-aid',
    title: 'Learn first aid',
    provider: 'British Red Cross',
    url: 'https://www.redcross.org.uk/first-aid/learn-first-aid',
    skills: ['first-aid'],
    cost: 'free',
    languages: ['en'],
    format: 'guide',
    checkedAt: CHECKED,
  },

  // Green & agriculture
  {
    id: 'solar-energy-basics',
    title: 'Solar Energy Basics',
    provider: 'State University of New York (Coursera)',
    url: 'https://www.coursera.org/learn/solar-energy-basics',
    skills: ['solar-installation', 'energy-efficiency', 'climate-literacy'],
    cost: 'free-audit',
    hours: 20,
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'unccelearn',
    title: 'UN CC:Learn climate courses',
    provider: 'United Nations (UN CC:Learn)',
    url: 'https://www.unccelearn.org/',
    skills: ['climate-literacy', 'energy-efficiency', 'circular-economy'],
    cost: 'low-cost',
    languages: ['en', 'es', 'fr', 'pt', 'ru', 'zh'],
    format: 'course',
    checkedAt: CHECKED,
  },
  {
    id: 'fao-elearning',
    title: 'FAO elearning Academy',
    provider: 'Food and Agriculture Organization of the UN',
    url: 'https://elearning.fao.org/',
    skills: ['climate-smart-farming', 'agribusiness', 'food-safety'],
    cost: 'free',
    languages: ['en', 'fr', 'es', 'ru', 'ar', 'zh', 'it', 'pt', 'tr'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // Language
  {
    id: 'duolingo',
    title: 'Duolingo',
    provider: 'Duolingo',
    url: 'https://www.duolingo.com/',
    skills: ['language-learning', 'english-workplace'],
    cost: 'free',
    languages: ['en', 'es', 'fr', 'pt', 'hi', 'ar', 'sw'],
    format: 'practice',
    checkedAt: CHECKED,
  },
  {
    id: 'bbc-learning-english',
    title: 'BBC Learning English',
    provider: 'BBC',
    url: 'https://www.bbc.co.uk/learningenglish',
    skills: ['english-workplace'],
    cost: 'free',
    languages: ['en'],
    format: 'course',
    checkedAt: CHECKED,
  },

  // National platforms
  {
    id: 'swayam',
    title: 'SWAYAM free university courses',
    provider: 'Government of India',
    url: 'https://swayam.gov.in/',
    skills: [
      'programming-basics',
      'data-analysis',
      'entrepreneurship',
      'statistics-basics',
      'english-workplace',
      'climate-smart-farming',
    ],
    cost: 'free',
    languages: ['en', 'hi'],
    format: 'course',
    regions: ['IN'],
    checkedAt: CHECKED,
  },
  {
    id: 'skill-india-digital',
    title: 'Skill India Digital Hub',
    provider: 'Ministry of Skill Development and Entrepreneurship',
    url: 'https://www.skillindiadigital.gov.in/',
    skills: [
      'digital-basics',
      'electrical-basics',
      'plumbing-basics',
      'solar-installation',
      'customer-service',
      'ai-literacy',
    ],
    cost: 'free',
    languages: ['en', 'hi'],
    format: 'course',
    regions: ['IN'],
    checkedAt: CHECKED,
  },
];
