import type { SourceRef, SupportResource } from './types';

/**
 * Crisis and support services. SAFETY-CRITICAL.
 *
 * Every entry was checked on 2026-09-29 against the service's own website, a government page,
 * or Find A Helpline (ThroughLine), whose listings are verified directly by the helplines.
 * Rules:
 *  - `hours` is only set when a source states it. No hours means "not stated", not "24/7".
 *  - `free` is only set when a source says calls are free or toll-free.
 *  - `languages` is only set when a source lists them.
 *  - Numbers are written the way people dial them locally.
 * When a service changes, update the entry and its `checkedAt`; never guess.
 */

const CHECKED = '2026-09-29';
const src = (url: string, title: string): SourceRef => ({ url, title, checkedAt: CHECKED });
const fah = (code: string, country: string): SourceRef =>
  src(`https://findahelpline.com/countries/${code}`, `Find A Helpline (ThroughLine): ${country}`);

export const SUPPORT_RESOURCES: SupportResource[] = [
  // ───────────────────────────── Global directories ─────────────────────────────
  {
    id: 'zz-find-a-helpline',
    country: 'ZZ',
    kind: 'directory',
    name: 'Find A Helpline',
    url: 'https://findahelpline.com',
    free: true,
    audience:
      'Free, verified helplines in 175+ countries — by phone, text or chat — for anyone who needs to talk.',
    sources: [
      src('https://findahelpline.com/', 'Find A Helpline (ThroughLine)'),
      src(
        'https://www.iasp.info/crisis-centres-helplines/',
        'International Association for Suicide Prevention: crisis centres and helplines',
      ),
    ],
  },
  {
    id: 'zz-befrienders-worldwide',
    country: 'ZZ',
    kind: 'directory',
    name: 'Befrienders Worldwide',
    url: 'https://befrienders.org/find-support-now/',
    free: true,
    audience:
      'A worldwide network of emotional support centres for people feeling lonely, in despair or suicidal. Search by country and language.',
    sources: [
      src('https://www.befrienders.org/', 'Befrienders Worldwide'),
      src('https://befrienders.org/find-support-now/', 'Befrienders Worldwide: find support now'),
    ],
  },
  {
    id: 'zz-child-helpline-international',
    country: 'ZZ',
    kind: 'directory',
    name: 'Child Helpline International',
    url: 'https://childhelplineinternational.org/helplines/',
    audience:
      'Find the child helpline in your country. For children and young people, and adults worried about a child.',
    sources: [
      src(
        'https://childhelplineinternational.org/helplines/',
        'Child Helpline International: find your local child helpline',
      ),
    ],
  },

  // ───────────────────────────── South Asia ─────────────────────────────
  {
    id: 'in-tele-manas',
    country: 'IN',
    kind: 'crisis-line',
    name: 'Tele MANAS',
    phone: '14416',
    url: 'https://telemanas.mohfw.gov.in/',
    hours: '24/7',
    free: true,
    audience:
      'Government mental health helpline for anyone in distress, in English and 20 Indian languages. You can also call 1-800-891-4416.',
    sources: [
      src(
        'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2022057',
        'PIB (Ministry of Health and Family Welfare): Tele-MANAS toll-free 14416 or 1-800-891-4416',
      ),
      src('https://findahelpline.com/organizations/tele-manas', 'Find A Helpline: Tele MANAS'),
      src(
        'https://www.digitalhealthnews.com/govt-integrates-kiran-mental-health-helpline-with-telemanas',
        'KIRAN helpline integrated into Tele-MANAS',
      ),
    ],
  },
  {
    id: 'in-vandrevala',
    country: 'IN',
    kind: 'crisis-line',
    name: 'Vandrevala Foundation',
    phone: '+91 9999 666 555',
    whatsapp: '+91 9999 666 555',
    hours: '24/7',
    free: true,
    audience: 'Free emotional support by call or WhatsApp for anyone struggling.',
    sources: [fah('in', 'India')],
  },
  {
    id: 'in-women-helpline-181',
    country: 'IN',
    kind: 'domestic-violence',
    name: 'Women Helpline 181',
    phone: '181',
    hours: '24/7',
    free: true,
    audience:
      'For any woman facing violence or in distress, or someone calling for her. Available in every state and union territory except West Bengal.',
    sources: [
      src(
        'https://wcd.gov.in/women/help',
        'Ministry of Women and Child Development: Women Helpline 181',
      ),
    ],
  },
  {
    id: 'in-ncw-14490',
    country: 'IN',
    kind: 'domestic-violence',
    name: 'National Commission for Women Helpline',
    phone: '14490',
    hours: '24/7',
    free: true,
    audience: 'For women and girls (18+) facing violence. Linked to the NCW line 7827 170 170.',
    sources: [
      src(
        'https://www.pib.gov.in/FactsheetDetails.aspx?id=150678&NoteId=150678&ModuleId=16&reg=48&lang=1',
        'PIB factsheet (July 2026): NCW Women Helpline 14490',
      ),
      src(
        'https://www.ncw.gov.in/ncw-cells/ncw-women-helpline/',
        'National Commission for Women: helpline',
      ),
    ],
  },
  {
    id: 'in-childline-1098',
    country: 'IN',
    kind: 'child-helpline',
    name: 'Child Helpline 1098',
    phone: '1098',
    hours: '24/7',
    audience:
      'For children in danger or distress, or adults worried about a child. Linked with 112.',
    sources: [
      src(
        'https://wcd.gov.in/child/child-helpline',
        'Ministry of Women and Child Development: Child Helpline 1098',
      ),
    ],
  },
  {
    id: 'pk-rozan',
    country: 'PK',
    kind: 'mental-health',
    name: 'Rozan Counselling Helpline',
    phone: '0304 111 1741',
    hours: '10:00–20:00, 7 days',
    audience: 'Confidential emotional support from trained counsellors.',
    sources: [
      src('https://rozan.org/rozan-counselling-helpline/', 'Rozan: counselling helpline'),
      fah('pk', 'Pakistan'),
    ],
  },
  {
    id: 'pk-punjab-women-1043',
    country: 'PK',
    kind: 'domestic-violence',
    name: 'Punjab Women Helpline 1043',
    phone: '1043',
    hours: '24/7',
    free: true,
    audience:
      'For women in Punjab facing domestic violence, harassment or discrimination. Legal and counselling support.',
    sources: [
      src(
        'https://pcsw.punjab.gov.pk/helpline_',
        'Punjab Commission on the Status of Women: helpline 1043',
      ),
    ],
  },
  {
    id: 'pk-child-1121',
    country: 'PK',
    kind: 'child-helpline',
    name: 'Child Protection Helpline 1121 (Punjab)',
    phone: '1121',
    audience: 'For children in Punjab facing violence, abuse, exploitation or neglect.',
    sources: [
      src(
        'https://cpwb.punjab.gov.pk/helpline',
        'Child Protection & Welfare Bureau Punjab: helpline 1121',
      ),
    ],
  },
  {
    id: 'bd-kaan-pete-roi',
    country: 'BD',
    kind: 'crisis-line',
    name: 'Kaan Pete Roi',
    phone: '+880 9612 119911',
    hours: '15:00–03:00 daily',
    audience: 'Emotional support and suicide prevention, from trained volunteers.',
    sources: [
      src(
        'https://lifeline-international.com/member/bangladesh/',
        'Lifeline International: Kaan Pete Roi',
      ),
      fah('bd', 'Bangladesh'),
    ],
  },
  {
    id: 'bd-109',
    country: 'BD',
    kind: 'domestic-violence',
    name: 'National Helpline 109 (violence against women and children)',
    phone: '109',
    hours: '24/7',
    free: true,
    audience:
      'For women and children facing domestic violence, child marriage, harassment or abuse.',
    sources: [
      src(
        'https://www.thedailystar.net/news/bangladesh/news/109-helpline-complaint-centre-or-info-hub-3608521',
        'The Daily Star: toll-free 24/7 National Helpline Centre 109',
      ),
    ],
  },
  {
    id: 'bd-child-1098',
    country: 'BD',
    kind: 'child-helpline',
    name: 'Child Helpline 1098',
    phone: '1098',
    hours: '24/7',
    free: true,
    languages: ['bn'],
    audience:
      'For children and young people who need help. Run by the Department of Social Services.',
    sources: [
      src(
        'https://childhelplineinternational.org/bangladesh-bangladesh-child-helpline-1098/',
        'Child Helpline International: Bangladesh Child Helpline 1098',
      ),
    ],
  },
  {
    id: 'np-1166',
    country: 'NP',
    kind: 'crisis-line',
    name: 'National Suicide Prevention Helpline 1166',
    phone: '1166',
    audience:
      'Government helpline for anyone in emotional distress or thinking about suicide. Free from Nepal Telecom phones; other networks may charge.',
    sources: [
      src(
        'https://nepal.un.org/en/241003-nepal%E2%80%99s-national-suicide-prevention-helpline-service-helping-save-lives',
        'UN Nepal / WHO: national suicide prevention helpline 1166',
      ),
      src(
        'https://www.who.int/nepal/news/detail/10-12-2025-unicef-and-who-applaud-the-launch-of-government-s-national-mental-health-campaign',
        'WHO Nepal (December 2025): National Suicide Prevention Helpline 1166',
      ),
    ],
  },
  {
    id: 'np-khabar-garaun-1145',
    country: 'NP',
    kind: 'domestic-violence',
    name: 'Khabar Garaun 1145',
    phone: '1145',
    sms: '1145',
    hours: '24/7',
    free: true,
    audience: 'National Women Commission helpline for anyone facing gender-based violence.',
    sources: [
      src('https://nwchelpline.gov.np/', 'National Women Commission: Khabar Garaun 1145'),
      fah('np', 'Nepal'),
    ],
  },
  {
    id: 'np-child-1098',
    country: 'NP',
    kind: 'child-helpline',
    name: 'Child Helpline Nepal 1098',
    phone: '1098',
    languages: ['ne'],
    audience: 'For children who need help or protection. Run by CWIN.',
    sources: [
      src(
        'https://childhelplineinternational.org/nepal-child-helpline-nepal-1098/',
        'Child Helpline International: Child Helpline Nepal 1098',
      ),
    ],
  },
  {
    id: 'lk-ccc-1333',
    country: 'LK',
    kind: 'crisis-line',
    name: 'CCCline 1333',
    phone: '1333',
    hours: '24/7',
    free: true,
    languages: ['si', 'ta', 'en'],
    audience:
      'Crisis support for anyone in distress or thinking about suicide. No phone credit needed.',
    sources: [src('https://1333.lk/', 'CCC Foundation: CCCline 1333'), fah('lk', 'Sri Lanka')],
  },
  {
    id: 'lk-1926',
    country: 'LK',
    kind: 'mental-health',
    name: 'National Mental Health Helpline 1926',
    phone: '1926',
    sms: '1926',
    hours: '24/7',
    free: true,
    audience: 'National Institute of Mental Health helpline, by phone or text.',
    sources: [
      src(
        'https://findahelpline.com/organizations/1926-national-mental-health-helpline',
        'Find A Helpline: 1926 National Mental Health Helpline',
      ),
      src('https://nimh.health.gov.lk/', 'National Institute of Mental Health, Sri Lanka'),
    ],
  },
  {
    id: 'lk-sumithrayo',
    country: 'LK',
    kind: 'crisis-line',
    name: 'Sri Lanka Sumithrayo',
    whatsapp: '0767 520 620',
    phone: '0707 308 308',
    hours: '09:00–16:00, 365 days a year',
    free: true,
    audience:
      'Befriending for people who feel overwhelmed, depressed or suicidal. WhatsApp: 0767 520 620.',
    sources: [src('https://srilankasumithrayo.lk/', 'Sri Lanka Sumithrayo')],
  },
  {
    id: 'lk-child-1929',
    country: 'LK',
    kind: 'child-helpline',
    name: 'National Child Protection Authority 1929',
    phone: '1929',
    hours: '24/7',
    free: true,
    languages: ['si', 'ta', 'en'],
    audience: 'Report abuse of a child, or get help as a child or young person.',
    sources: [
      src(
        'https://childprotection.gov.lk/en/what-we-do/1929-call-centre-helpline',
        'National Child Protection Authority: 1929 helpline',
      ),
    ],
  },
  {
    id: 'lk-women-in-need',
    country: 'LK',
    kind: 'domestic-violence',
    name: 'Women In Need Helpline',
    phone: '077 567 6555',
    hours: '24/7',
    free: true,
    audience: 'For women and children facing domestic violence or abuse.',
    sources: [fah('lk', 'Sri Lanka')],
  },

  // ───────────────────────────── Southeast Asia ─────────────────────────────
  {
    id: 'id-healing119',
    country: 'ID',
    kind: 'crisis-line',
    name: 'Healing119.id',
    phone: '119',
    url: 'https://healing119.id',
    hours: '24/7',
    free: true,
    audience:
      'Ministry of Health mental health support for anyone in distress or thinking about suicide. Call 119 and choose extension 8, or use WhatsApp via the website.',
    sources: [
      src(
        'https://infopublik.id/kategori/layanan-publik/952502/healing119-id-layanan-kesehatan-mental-24-jam-teman-bicara-yang-siap-mendengar',
        'InfoPublik (December 2025): Healing119.id, 24-hour mental health service',
      ),
      src(
        'https://kesprimkom.kemkes.go.id/konten/158/151/0/cegah-bunuh-diri-dukung-kesehatan-jiwa-kenali-layanan-healing119-id',
        'Kemenkes: Healing119.id (call 119 ext. 8)',
      ),
    ],
  },
  {
    id: 'id-sapa-129',
    country: 'ID',
    kind: 'domestic-violence',
    name: 'SAPA 129',
    whatsapp: '0811 1129 129',
    phone: '129',
    url: 'https://laporsapa129.kemenpppa.go.id/',
    audience: 'Report violence against women and children, by phone or WhatsApp 0811 1129 129.',
    sources: [src('https://laporsapa129.kemenpppa.go.id/', 'KemenPPPA: SAPA 129')],
  },
  {
    id: 'id-tepsa',
    country: 'ID',
    kind: 'child-helpline',
    name: 'TePSA (Telepon Pelayanan Sosial Anak)',
    phone: '1500 771',
    audience: 'Ministry of Social Affairs line for children who need help.',
    sources: [fah('id', 'Indonesia')],
  },
  {
    id: 'ph-ncmh',
    country: 'PH',
    kind: 'crisis-line',
    name: 'NCMH Crisis Hotline',
    phone: '1553',
    hours: '24/7',
    free: true,
    audience:
      'National Center for Mental Health crisis line. Also 1800-1888-1553, 0919 057 1553, 0966 351 4518 or 0917 899 8727.',
    sources: [
      src(
        'https://pia.gov.ph/news/luzon/doh-mental-health-programs-crisis-hotlines-available-this-undas/',
        'Philippine Information Agency (October 2025): DOH crisis hotlines',
      ),
      fah('ph', 'Philippines'),
    ],
  },
  {
    id: 'ph-in-touch',
    country: 'PH',
    kind: 'crisis-line',
    name: 'In Touch Crisis Line',
    phone: '+63 2 8893 7603',
    hours: '24/7',
    free: true,
    audience: 'Free, anonymous crisis support by phone.',
    sources: [
      src('https://in-touch.org/contact-us/', 'In Touch Community Services: 24/7 crisis line'),
    ],
  },
  {
    id: 'ph-aleng-pulis',
    country: 'PH',
    kind: 'domestic-violence',
    name: 'Aleng Pulis Hotline (PNP)',
    phone: '0920 907 1717',
    hours: '24/7',
    audience: 'Police hotline for violence against women and children.',
    sources: [
      src(
        'https://pia.gov.ph/gender-and-development/new-aleng-pulis-hotline-to-beef-up-vawc-response/',
        'Philippine Information Agency: Aleng Pulis 24/7 hotline',
      ),
    ],
  },
  {
    id: 'ph-makabata-1383',
    country: 'PH',
    kind: 'child-helpline',
    name: 'Makabata Helpline 1383',
    phone: '1383',
    audience: 'Report child abuse, or get help as a child. Council for the Welfare of Children.',
    sources: [
      src(
        'https://www.dswd.gov.ph/dswd-urges-public-to-report-child-abuse-cases-to-makabata-helpline-1383/',
        'DSWD: Makabata Helpline 1383',
      ),
    ],
  },
  {
    id: 'vn-ngay-mai',
    country: 'VN',
    kind: 'crisis-line',
    name: 'Đường dây nóng Ngày Mai',
    phone: '096 306 1414',
    hours: 'Wed–Sun 13:00–20:30',
    free: true,
    languages: ['vi'],
    audience:
      'Free psychological first aid for people in crisis, especially young people with depression.',
    sources: [src('https://duongdaynongngaymai.vn/hotline/', 'Ngày Mai hotline')],
  },
  {
    id: 'vn-child-111',
    country: 'VN',
    kind: 'child-helpline',
    name: 'National Child Protection Hotline 111',
    phone: '111',
    hours: '24/7',
    free: true,
    audience: 'Report a child in danger, or get help as a child.',
    sources: [
      src(
        'https://sotuphap.daklak.gov.vn/tong-dai-dien-thoai-quoc-gia-bao-ve-tre-em-111-chinh-thuc-hoat-dong-4448.html',
        'Dak Lak Department of Justice: national child protection hotline 111',
      ),
    ],
  },
  {
    id: 'vn-peace-house',
    country: 'VN',
    kind: 'domestic-violence',
    name: 'Peace House Shelter (CWD)',
    phone: '1900 969 680',
    hours: '08:00–17:00',
    audience: 'Support and safe shelter for women facing domestic violence.',
    sources: [
      src(
        'https://cwd.vn/en/peace-house-shelters',
        'Center for Women and Development: Peace House',
      ),
    ],
  },
  {
    id: 'th-1323',
    country: 'TH',
    kind: 'crisis-line',
    name: 'Mental Health Hotline 1323',
    phone: '1323',
    hours: '24/7',
    free: true,
    languages: ['th'],
    audience: 'Department of Mental Health counselling by phone or online chat.',
    sources: [fah('th', 'Thailand')],
  },
  {
    id: 'th-samaritans',
    country: 'TH',
    kind: 'crisis-line',
    name: 'Samaritans of Thailand',
    phone: '02 113 6789',
    hours: 'Thai: daily 12:00–22:00 (press 1). English: press 2.',
    languages: ['th', 'en'],
    audience: 'Emotional support and suicide prevention.',
    sources: [src('https://www.samaritansthai.com/contactus/', 'Samaritans of Thailand: contact')],
  },
  {
    id: 'th-1300',
    country: 'TH',
    kind: 'domestic-violence',
    name: 'Social Assistance Center 1300',
    phone: '1300',
    hours: '24/7',
    audience:
      'Government help for domestic violence, families in hardship, older people and people with disabilities.',
    sources: [
      src(
        'https://1300thailand.m-society.go.th/page/29',
        'Ministry of Social Development: 1300 contact channels',
      ),
      fah('th', 'Thailand'),
    ],
  },
  {
    id: 'th-childline-1387',
    country: 'TH',
    kind: 'child-helpline',
    name: 'Childline Thailand (Saidek 1387)',
    phone: '1387',
    hours: '24/7',
    audience: 'For any child under 18 living in Thailand.',
    sources: [src('https://www.childlinethailand.org/', 'Childline Thailand Foundation')],
  },
  {
    id: 'my-heal-15555',
    country: 'MY',
    kind: 'mental-health',
    name: 'Talian HEAL 15555',
    phone: '15555',
    hours: 'Daily 08:00–24:00, including public holidays',
    audience: 'Ministry of Health counselling for stress, depression or psychological crisis.',
    sources: [
      src(
        'https://malaysiaaktif.my/2025/10/dail-talian-heal-15555-langkah-awal-bendung-krisis-psikologi/',
        'Malaysia Aktif (October 2025): Talian HEAL 15555 hours',
      ),
      fah('my', 'Malaysia'),
    ],
  },
  {
    id: 'my-befrienders-kl',
    country: 'MY',
    kind: 'crisis-line',
    name: 'Befrienders Kuala Lumpur',
    phone: '03 7627 2929',
    hours: '24/7',
    free: true,
    audience: 'Emotional support for anyone feeling lonely, distressed or suicidal.',
    sources: [src('https://www.befrienders.org.my/', 'Befrienders KL')],
  },
  {
    id: 'my-talian-kasih',
    country: 'MY',
    kind: 'domestic-violence',
    name: 'Talian Kasih 15999',
    whatsapp: '019 261 5999',
    phone: '15999',
    hours: '24/7',
    audience:
      'For women, children, older people and others facing abuse or family crisis. WhatsApp: 019 261 5999.',
    sources: [
      src(
        'https://www.malaysia.gov.my/en/personas/women/undang-undang-dan-perlindungan-wanita/talian-kasih-15999',
        'MyGOV: Talian Kasih 15999',
      ),
    ],
  },
  {
    id: 'sg-mindline-1771',
    country: 'SG',
    kind: 'mental-health',
    name: 'National mindline 1771',
    whatsapp: '+65 6669 1771',
    phone: '1771',
    url: 'https://www.mindline.sg',
    hours: '24/7',
    audience:
      'Ministry of Health mental health support by call, WhatsApp (+65 6669 1771) or webchat.',
    sources: [
      src(
        'https://www.moh.gov.sg/newsroom/national-mindline-1771-to-provide--round-the-clock-support-for-mental-health/',
        'Ministry of Health Singapore: national mindline 1771',
      ),
    ],
  },
  {
    id: 'sg-sos-1767',
    country: 'SG',
    kind: 'crisis-line',
    name: 'Samaritans of Singapore (SOS)',
    whatsapp: '9151 1767',
    phone: '1767',
    hours: '24/7',
    audience:
      'Crisis support for anyone in distress or thinking about suicide. CareText on WhatsApp: 9151 1767.',
    sources: [src('https://www.sos.org.sg/', 'Samaritans of Singapore')],
  },
  {
    id: 'sg-navh',
    country: 'SG',
    kind: 'domestic-violence',
    name: 'National Anti-Violence and Sexual Harassment Helpline',
    phone: '1800 777 0000',
    audience:
      'Report family violence or sexual harassment. In danger now: police 999, or SMS 70999.',
    sources: [
      src(
        'https://www.msf.gov.sg/what-we-do/break-the-silence/get-help/i-want-to-report-domestic-violence',
        'Ministry of Social and Family Development: report domestic violence',
      ),
    ],
  },

  // ───────────────────────────── East Asia ─────────────────────────────
  {
    id: 'cn-12356',
    country: 'CN',
    kind: 'mental-health',
    name: '12356 National Psychological Assistance Hotline',
    phone: '12356',
    languages: ['zh'],
    audience:
      'National unified line for psychological counselling and crisis intervention, open in every province. Lines run at least 18 hours a day.',
    sources: [
      src(
        'https://www.beijing.gov.cn/ywdt/zybwdt/202412/t20241226_3973938.html',
        'Beijing Municipal Government: 12356 national psychological assistance hotline',
      ),
      src(
        'https://www.news.cn/politics/20250508/6a76fdf3d82b4efca742793d3e563643/c.html',
        'Xinhua (May 2025): 12356 open in all 31 provinces',
      ),
    ],
  },
  {
    id: 'cn-hope-24',
    country: 'CN',
    kind: 'crisis-line',
    name: 'Hope 24 Hotline (希望24热线)',
    phone: '400 161 9995',
    languages: ['zh'],
    audience: 'Suicide prevention and emotional support.',
    sources: [fah('cn', 'China')],
  },
  {
    id: 'cn-lifeline-china',
    country: 'CN',
    kind: 'crisis-line',
    name: 'Lifeline China',
    phone: '400 821 1215',
    languages: ['en'],
    audience: 'Emotional support in English, for people living in China.',
    sources: [fah('cn', 'China')],
  },
  {
    id: 'cn-12338',
    country: 'CN',
    kind: 'domestic-violence',
    name: 'Women’s Rights Hotline 12338',
    phone: '12338',
    languages: ['zh'],
    audience: 'All-China Women’s Federation hotline, including help with domestic violence.',
    sources: [
      src(
        'https://womenofchina.cn/womenofchina/projects/2411/1917-1.htm',
        'Women of China (ACWF): the 12338 hotline',
      ),
    ],
  },
  {
    id: 'cn-12355',
    country: 'CN',
    kind: 'child-helpline',
    name: '12355 Youth Service Line',
    phone: '12355',
    languages: ['zh'],
    audience: 'Psychological and legal advice for children and young people.',
    sources: [
      src(
        'https://www.gqt.org.cn/xxgk/zdgz/202209/t20220921_789696.htm',
        'Communist Youth League: 12355 youth service desk',
      ),
    ],
  },
  {
    id: 'jp-inochi-sos',
    country: 'JP',
    kind: 'crisis-line',
    name: '#いのちSOS (Inochi SOS)',
    phone: '0120 061 338',
    hours: '24/7',
    free: true,
    languages: ['ja'],
    audience: 'Suicide prevention line for anyone thinking about ending their life.',
    sources: [
      src(
        'https://www.mhlw.go.jp/mamorouyokokoro/soudan/tel/',
        'Ministry of Health, Labour and Welfare: phone consultation',
      ),
    ],
  },
  {
    id: 'jp-yorisoi',
    country: 'JP',
    kind: 'crisis-line',
    name: 'よりそいホットライン (Yorisoi Hotline)',
    phone: '0120 279 338',
    hours: '24/7',
    free: true,
    audience: 'Support for any worry, including thoughts of suicide, violence or discrimination.',
    sources: [
      src(
        'https://www.mhlw.go.jp/mamorouyokokoro/soudan/tel/',
        'Ministry of Health, Labour and Welfare: phone consultation',
      ),
    ],
  },
  {
    id: 'jp-anata-no-ibasho',
    country: 'JP',
    kind: 'chat',
    name: 'あなたのいばしょ (Anata no Ibasho)',
    url: 'https://talkme.jp/',
    hours: '24/7',
    free: true,
    languages: ['ja'],
    audience: 'Anonymous chat support for anyone, any time.',
    sources: [
      src(
        'https://www.mhlw.go.jp/mamorouyokokoro/soudan/sns/',
        'Ministry of Health, Labour and Welfare: SNS and chat consultation',
      ),
    ],
  },
  {
    id: 'jp-tell-lifeline',
    country: 'JP',
    kind: 'crisis-line',
    name: 'TELL Lifeline',
    phone: '0800 300 8355',
    url: 'https://telljp.com/lifeline/',
    hours: 'Sat 09:00 – Mon 23:00; Tue–Thu 09:00–23:00; Fri 09:00–02:00',
    free: true,
    languages: ['en'],
    audience: 'Free emotional support in English for anyone in Japan.',
    sources: [src('https://telljp.com/lifeline/', 'TELL Lifeline')],
  },
  {
    id: 'jp-dv-soudan-plus',
    country: 'JP',
    kind: 'domestic-violence',
    name: 'DV相談＋ (DV Soudan Plus)',
    phone: '0120 279 889',
    url: 'https://soudanplus.jp/',
    hours: 'Phone 24/7; chat 12:00–22:00',
    audience: 'Cabinet Office domestic violence support, with chat in 10 languages.',
    sources: [src('https://soudanplus.jp/', 'DV相談＋ (Cabinet Office)')],
  },
  {
    id: 'jp-kodomo-sos',
    country: 'JP',
    kind: 'child-helpline',
    name: '24時間子供SOSダイヤル (24-hour Child SOS)',
    phone: '0120 0 78310',
    hours: '24/7',
    free: true,
    audience: 'For children and parents with any worry, including bullying.',
    sources: [
      src(
        'https://www.mhlw.go.jp/mamorouyokokoro/soudan/tel/',
        'Ministry of Health, Labour and Welfare: phone consultation',
      ),
    ],
  },
  {
    id: 'kr-109',
    country: 'KR',
    kind: 'crisis-line',
    name: 'Suicide Prevention Hotline 109',
    phone: '109',
    hours: '24/7',
    languages: ['ko'],
    audience:
      'National suicide prevention line (all earlier lines merged into 109 in January 2024).',
    sources: [
      src(
        'https://www.khan.co.kr/article/202511010800041',
        'Kyunghyang Shinmun (November 2025): the 109 hotline',
      ),
      src(
        'https://www.koreatimes.co.kr/southkorea/health/20260601/korea-increases-hotline-staff-for-suicide-prevention-calls-boosts-multilingual-support',
        'The Korea Times (June 2026): 109 hotline staffing',
      ),
    ],
  },
  {
    id: 'kr-lifeline',
    country: 'KR',
    kind: 'crisis-line',
    name: 'Lifeline Korea',
    phone: '1588 9191',
    hours: '24/7',
    audience: 'Counselling for any concern.',
    sources: [fah('kr', 'South Korea')],
  },
  {
    id: 'kr-1366',
    country: 'KR',
    kind: 'domestic-violence',
    name: 'Women’s Emergency Line 1366',
    phone: '1366',
    hours: '24/7',
    audience: 'For anyone facing domestic violence, sexual violence, stalking or dating violence.',
    sources: [
      src(
        'https://www.mogef.go.kr/cc/wcc/cc_wcc_f001.do',
        'Ministry of Gender Equality and Family: 1366',
      ),
    ],
  },
  {
    id: 'kr-danuri',
    country: 'KR',
    kind: 'mental-health',
    name: 'Danuri Helpline',
    phone: '1577 1366',
    hours: '24/7',
    audience: 'Multilingual support and interpretation for migrants and multicultural families.',
    sources: [
      src(
        'https://www.gov.uk/foreign-travel-advice/south-korea/getting-help',
        'UK FCDO: South Korea – getting help',
      ),
      fah('kr', 'South Korea'),
    ],
  },
  {
    id: 'kr-youth-1388',
    country: 'KR',
    kind: 'child-helpline',
    name: 'Youth Counselling 1388',
    phone: '1388',
    audience: 'Counselling for children and young people.',
    sources: [fah('kr', 'South Korea')],
  },

  // ───────────────────────────── Middle East & North Africa ─────────────────────────────
  {
    id: 'ae-sakina',
    country: 'AE',
    kind: 'mental-health',
    name: '800 SAKINA (Abu Dhabi)',
    phone: '800 725462',
    hours: '24/7',
    languages: ['ar', 'en'],
    audience:
      'Department of Health mental health support line, with services for children and families.',
    sources: [
      src(
        'https://www.doh.gov.ae/en/news/doh-activates-247-mental-health-support-hotline-800-sakina-(725462)',
        'Department of Health Abu Dhabi (March 2026): 800 SAKINA',
      ),
    ],
  },
  {
    id: 'ae-itmaen',
    country: 'AE',
    kind: 'mental-health',
    name: 'Itma’en Mental Health Support (Dubai)',
    phone: '800 506',
    free: true,
    audience: 'Free, confidential psychological first aid run by Dubai Health.',
    sources: [
      src(
        'https://www.thenationalnews.com/news/uae/2026/03/14/dubai-launches-mental-health-hotline-to-support-public-as-iran-crisis-continues/',
        'The National (March 2026): Dubai mental health hotline 800 506',
      ),
    ],
  },
  {
    id: 'ae-child-116111',
    country: 'AE',
    kind: 'child-helpline',
    name: 'Child Protection Centre 116111',
    phone: '116111',
    audience: 'Report child abuse to the Ministry of Interior.',
    sources: [
      src(
        'https://u.ae/en/information-and-services/justice-safety-and-the-law/children-safety/report-child-abuse',
        'UAE Government portal: report child abuse',
      ),
    ],
  },
  {
    id: 'ae-dfwac',
    country: 'AE',
    kind: 'domestic-violence',
    name: 'Dubai Foundation for Women and Children',
    phone: '800 111',
    sms: '5111',
    hours: 'Mon–Thu 07:30–15:30, Fri 07:30–12:00',
    audience: 'For women and children facing domestic violence, abuse or trafficking.',
    sources: [src('https://www.dfwac.ae/', 'Dubai Foundation for Women and Children')],
  },
  {
    id: 'sa-ncmh',
    country: 'SA',
    kind: 'mental-health',
    name: 'National Center for Mental Health Promotion',
    phone: '920033360',
    hours: '08:00–20:00',
    languages: ['ar'],
    audience: 'Psychological consultation by phone from anywhere in the Kingdom.',
    sources: [
      src(
        'https://www.moh.gov.sa/en/Ministry/Information-and-services/Pages/psychiatry.aspx',
        'Ministry of Health: psychological consultation line 920033360',
      ),
    ],
  },
  {
    id: 'sa-1919',
    country: 'SA',
    kind: 'domestic-violence',
    name: 'Domestic Violence Reporting Center 1919',
    phone: '1919',
    free: true,
    audience: 'Report family violence. For citizens, residents and visitors.',
    sources: [
      src(
        'https://www.hrsd.gov.sa/en/ministry-services/services/%D8%A7%D9%84%D8%A5%D8%A8%D9%84%D8%A7%D8%BA-%D8%B9%D9%86-%D8%A7%D9%84%D8%B9%D9%86%D9%81-%D8%A7%D9%84%D8%A3%D8%B3%D8%B1%D9%8A',
        'Ministry of Human Resources and Social Development: report domestic violence',
      ),
    ],
  },
  {
    id: 'sa-child-116111',
    country: 'SA',
    kind: 'child-helpline',
    name: 'Child Helpline 116111',
    phone: '116111',
    free: true,
    audience: 'Advice and support for children, run by the National Family Safety Program.',
    sources: [src('https://www.spa.gov.sa/2328960', 'Saudi Press Agency: child helpline 116111')],
  },
  {
    id: 'eg-16328',
    country: 'EG',
    kind: 'crisis-line',
    name: 'Mental Health Hotline 16328',
    phone: '16328',
    hours: '24/7',
    free: true,
    languages: ['ar'],
    audience:
      'Ministry of Health psychological support, including emergency help. You can also call 02 2081 6831.',
    sources: [
      src(
        'https://www.elwatannews.com/news/details/8264064',
        'El Watan (April 2026): 16328 mental health hotline',
      ),
      src(
        'https://help.unhcr.org/egypt/en/health-services/mental-health/',
        'UNHCR Egypt: mental health services',
      ),
    ],
  },
  {
    id: 'eg-child-16000',
    country: 'EG',
    kind: 'child-helpline',
    name: 'Child Helpline 16000',
    whatsapp: '0110 212 1600',
    phone: '16000',
    hours: '24/7',
    free: true,
    audience: 'Report abuse or danger to a child. WhatsApp: 0110 212 1600.',
    sources: [
      src(
        'https://www.elwatannews.com/news/details/8292333',
        'El Watan (May 2026): child helpline 16000',
      ),
    ],
  },
  {
    id: 'eg-ncw-15115',
    country: 'EG',
    kind: 'domestic-violence',
    name: 'National Council for Women Complaints Office',
    whatsapp: '0100 752 5600',
    phone: '15115',
    hours: '09:00–21:00 daily',
    audience: 'For women and girls facing violence or discrimination. WhatsApp: 0100 752 5600.',
    sources: [
      src(
        'https://gate.ahram.org.eg/News/4960144.aspx',
        'Al-Ahram (September 2024): NCW complaints office',
      ),
    ],
  },
  {
    id: 'tr-alo-183',
    country: 'TR',
    kind: 'domestic-violence',
    name: 'ALO 183 Social Support Line',
    phone: '183',
    sms: '183',
    hours: '24/7',
    languages: ['tr'],
    audience:
      'Ministry of Family and Social Services line for violence against women and children, and support for families, older people and people with disabilities.',
    sources: [
      src(
        'https://www.aile.gov.tr/sss/engelli-ve-yasli-hizmetleri-genel-mudurlugu/alo-183-sosyal-destek/',
        'Ministry of Family and Social Services: ALO 183',
      ),
    ],
  },
  {
    id: 'ma-unfm-8350',
    country: 'MA',
    kind: 'domestic-violence',
    name: 'Ligne verte 8350 (UNFM)',
    phone: '8350',
    audience: 'Green line to report violence against women.',
    sources: [
      src(
        'https://www.leconomiste.com/article/1060398-violence-contre-les-femmes-appelez-le-8350',
        'L’Economiste: violence against women, call 8350',
      ),
      fah('ma', 'Morocco'),
    ],
  },

  // ───────────────────────────── Sub-Saharan Africa ─────────────────────────────
  {
    id: 'ng-surpin',
    country: 'NG',
    kind: 'crisis-line',
    name: 'SURPIN Lifeline',
    phone: '0800 078 7746',
    url: 'https://surpinng.com/',
    hours: '24/7',
    free: true,
    audience:
      'Crisis support for anyone with suicidal thoughts, depression, anxiety or substance use.',
    sources: [
      src('https://surpinng.com/', 'SURPIN (Suicide Research and Prevention Initiative)'),
      fah('ng', 'Nigeria'),
    ],
  },
  {
    id: 'ng-mani',
    country: 'NG',
    kind: 'mental-health',
    name: 'Mentally Aware Nigeria Initiative (MANI)',
    phone: '0809 111 6264',
    sms: '0809 111 6264',
    url: 'https://www.mentallyaware.org/',
    free: true,
    audience: 'Free, confidential support, mostly for young people.',
    sources: [fah('ng', 'Nigeria'), src('https://www.mentallyaware.org/', 'MANI')],
  },
  {
    id: 'ng-warif',
    country: 'NG',
    kind: 'domestic-violence',
    name: 'WARIF Helpline',
    phone: '0800 9210 0009',
    hours: '24/7',
    free: true,
    audience: 'For survivors of rape or sexual violence: medical care, counselling and legal help.',
    sources: [
      src('https://www.warifng.org/', 'Women at Risk International Foundation'),
      fah('ng', 'Nigeria'),
    ],
  },
  {
    id: 'ng-cece-yara',
    country: 'NG',
    kind: 'child-helpline',
    name: 'Cece Yara Child Helpline',
    phone: '0800 800 8001',
    hours: '24/7',
    free: true,
    audience: 'For children who are being sexually abused or are at risk, and their families.',
    sources: [src('https://ceceyara.org/', 'Cece Yara Foundation')],
  },
  {
    id: 'ke-red-cross-1199',
    country: 'KE',
    kind: 'crisis-line',
    name: 'Kenya Red Cross 1199',
    phone: '1199',
    free: true,
    audience: 'Free phone counselling and psychological crisis support, as well as emergency help.',
    sources: [
      src(
        'https://hapakenya.com/2026/03/09/how-to-contact-emergency-services-in-nairobi-nationwide/',
        'HapaKenya (March 2026): emergency and mental health numbers',
      ),
      src(
        'https://x.com/KenyaRedCross/status/1050269966132539393',
        'Kenya Red Cross: free counselling on toll-free 1199',
      ),
    ],
  },
  {
    id: 'ke-befrienders',
    country: 'KE',
    kind: 'crisis-line',
    name: 'Befrienders Kenya',
    whatsapp: '+254 722 178 177',
    phone: '+254 722 178 177',
    sms: '+254 722 178 177',
    hours: 'Mon–Fri',
    free: true,
    audience: 'Suicide prevention and emotional support, by call, SMS or WhatsApp.',
    sources: [fah('ke', 'Kenya')],
  },
  {
    id: 'ke-gbv-1195',
    country: 'KE',
    kind: 'domestic-violence',
    name: 'National GBV Helpline 1195',
    phone: '1195',
    hours: '24/7',
    free: true,
    audience: 'For survivors of gender-based violence: counselling, referrals and emergency help.',
    sources: [
      src(
        'https://africa.unwomen.org/en/stories/news/2024/10/kenyas-national-toll-free-helpline-1195-a-lifeline-for-gender-based-violence-survivors',
        'UN Women Africa: Kenya’s national toll-free helpline 1195',
      ),
    ],
  },
  {
    id: 'ke-child-116',
    country: 'KE',
    kind: 'child-helpline',
    name: 'National Child Helpline 116',
    whatsapp: '+254 722 116 116',
    phone: '116',
    hours: '24/7',
    free: true,
    audience: 'For children, or anyone reporting harm to a child. WhatsApp: +254 722 116 116.',
    sources: [
      src('https://www.childlinekenya.co.ke/', 'Childline Kenya: National Child Helpline 116'),
    ],
  },
  {
    id: 'gh-mha',
    country: 'GH',
    kind: 'crisis-line',
    name: 'National Mental Health and Suicide Prevention Helpline',
    phone: '0800 678 678',
    free: true,
    audience: 'Mental Health Authority line for anyone who is struggling.',
    sources: [fah('gh', 'Ghana')],
  },
  {
    id: 'gh-orange-support',
    country: 'GH',
    kind: 'domestic-violence',
    name: 'Orange Support Centre',
    phone: '0800 111 222',
    free: true,
    audience: 'Report sexual or gender-based violence and get counselling, legal and medical help.',
    sources: [
      src(
        'https://gna.org.gh/2024/11/government-resolves-to-end-gender-based-violence/',
        'Ghana News Agency (November 2024): Orange Support Centre toll-free line',
      ),
    ],
  },
  {
    id: 'za-sadag',
    country: 'ZA',
    kind: 'crisis-line',
    name: 'SADAG Suicide Crisis Helpline',
    phone: '0800 567 567',
    hours: '24/7',
    free: true,
    audience: 'For anyone having thoughts of suicide, or worried about someone.',
    sources: [
      src('https://www.sadag.org/', 'South African Depression and Anxiety Group'),
      fah('za', 'South Africa'),
    ],
  },
  {
    id: 'za-lifeline',
    country: 'ZA',
    kind: 'crisis-line',
    name: 'LifeLine South Africa',
    phone: '0861 322 322',
    hours: '24/7',
    audience: 'Counselling for anyone in crisis.',
    sources: [fah('za', 'South Africa')],
  },
  {
    id: 'za-gbv-command-centre',
    country: 'ZA',
    kind: 'domestic-violence',
    name: 'Gender-Based Violence Command Centre',
    phone: '0800 428 428',
    free: true,
    audience: 'Support for anyone facing gender-based violence.',
    sources: [fah('za', 'South Africa')],
  },
  {
    id: 'za-childline',
    country: 'ZA',
    kind: 'child-helpline',
    name: 'Childline South Africa',
    phone: '116',
    hours: '24/7',
    free: true,
    audience: 'For children and parents.',
    sources: [fah('za', 'South Africa')],
  },
  {
    id: 'ug-mifumi',
    country: 'UG',
    kind: 'domestic-violence',
    name: 'MIFUMI Domestic Violence Helpline',
    phone: '0800 200 250',
    audience: 'For women and children facing domestic violence or abuse.',
    sources: [fah('ug', 'Uganda')],
  },
  {
    id: 'ug-police-gbv',
    country: 'UG',
    kind: 'domestic-violence',
    name: 'Uganda Police GBV Desk',
    phone: '0800 199 195',
    audience: 'Report gender-based violence to the police.',
    sources: [fah('ug', 'Uganda')],
  },
  {
    id: 'tz-child-116',
    country: 'TZ',
    kind: 'child-helpline',
    name: 'National Child Helpline 116',
    phone: '116',
    sms: '116',
    hours: '24/7',
    free: true,
    audience: 'For children, young people and parents.',
    sources: [fah('tz', 'Tanzania')],
  },
  {
    id: 'tz-afya-199',
    country: 'TZ',
    kind: 'mental-health',
    name: 'Afya Call Centre 199',
    phone: '199',
    sms: '199',
    free: true,
    audience: 'Ministry of Health line for health questions and support.',
    sources: [fah('tz', 'Tanzania')],
  },
  {
    id: 'rw-gbv-3512',
    country: 'RW',
    kind: 'domestic-violence',
    name: 'Isange / GBV line 3512',
    phone: '3512',
    audience: 'Rwanda National Police line for gender-based violence.',
    sources: [
      src(
        'https://www.police.gov.rw/fileadmin/user_upload/Tender_Files/Rwanda_National_Police.pdf',
        'Rwanda National Police: emergency and toll-free numbers',
      ),
    ],
  },
  {
    id: 'rw-child-116',
    country: 'RW',
    kind: 'child-helpline',
    name: 'Child Helpline 116',
    phone: '116',
    audience: 'For children who need help or protection.',
    sources: [
      src(
        'https://www.police.gov.rw/fileadmin/user_upload/Tender_Files/Rwanda_National_Police.pdf',
        'Rwanda National Police: emergency and toll-free numbers',
      ),
    ],
  },

  // ───────────────────────────── Europe ─────────────────────────────
  {
    id: 'gb-samaritans',
    country: 'GB',
    kind: 'crisis-line',
    name: 'Samaritans',
    phone: '116 123',
    url: 'https://www.samaritans.org',
    hours: '24/7',
    free: true,
    audience:
      'Someone to talk to about anything, from any phone. Welsh language line: 0808 164 0123.',
    sources: [
      src(
        'https://www.samaritans.org/how-we-can-help/contact-samaritan/',
        'Samaritans: contact us',
      ),
    ],
  },
  {
    id: 'gb-shout',
    country: 'GB',
    kind: 'text-line',
    name: 'Shout',
    sms: '85258',
    smsKeyword: 'SHOUT',
    url: 'https://giveusashout.org',
    hours: '24/7',
    free: true,
    audience: 'Text support for anyone struggling to cope.',
    sources: [src('https://giveusashout.org/', 'Shout 85258')],
  },
  {
    id: 'gb-national-da-helpline',
    country: 'GB',
    kind: 'domestic-violence',
    name: 'National Domestic Abuse Helpline (Refuge)',
    phone: '0808 2000 247',
    url: 'https://www.nationaldahelpline.org.uk',
    hours: '24/7',
    free: true,
    audience: 'For anyone experiencing domestic abuse, or worried about someone.',
    sources: [src('https://www.nationaldahelpline.org.uk/', 'National Domestic Abuse Helpline')],
  },
  {
    id: 'gb-childline',
    country: 'GB',
    kind: 'child-helpline',
    name: 'Childline',
    phone: '0800 1111',
    url: 'https://www.childline.org.uk',
    hours: '24/7',
    free: true,
    audience: 'For children and young people, by phone or online chat.',
    sources: [src('https://www.childline.org.uk/', 'Childline')],
  },
  {
    id: 'ie-samaritans',
    country: 'IE',
    kind: 'crisis-line',
    name: 'Samaritans Ireland',
    phone: '116 123',
    hours: '24/7',
    free: true,
    audience: 'Someone to talk to about anything.',
    sources: [
      src(
        'https://www.samaritans.org/how-we-can-help/contact-samaritan/',
        'Samaritans: contact us',
      ),
      fah('ie', 'Ireland'),
    ],
  },
  {
    id: 'ie-pieta',
    country: 'IE',
    kind: 'crisis-line',
    name: 'Pieta',
    phone: '1800 247 247',
    sms: '51444',
    hours: '24/7',
    free: true,
    audience: 'For people thinking about suicide or self-harm, and people bereaved by suicide.',
    sources: [fah('ie', 'Ireland')],
  },
  {
    id: 'ie-text-50808',
    country: 'IE',
    kind: 'text-line',
    name: '50808',
    sms: '50808',
    hours: '24/7',
    free: true,
    audience: 'Free, anonymous text support for anyone going through a hard time.',
    sources: [fah('ie', 'Ireland')],
  },
  {
    id: 'ie-womens-aid',
    country: 'IE',
    kind: 'domestic-violence',
    name: 'Women’s Aid 24hr National Freephone Helpline',
    phone: '1800 341 900',
    hours: '24/7',
    free: true,
    audience: 'For women experiencing domestic abuse.',
    sources: [fah('ie', 'Ireland')],
  },
  {
    id: 'ie-childline',
    country: 'IE',
    kind: 'child-helpline',
    name: 'Childline (ISPCC)',
    phone: '1800 666 666',
    hours: '24/7',
    free: true,
    audience: 'For children and young people.',
    sources: [fah('ie', 'Ireland')],
  },
  {
    id: 'de-telefonseelsorge',
    country: 'DE',
    kind: 'crisis-line',
    name: 'TelefonSeelsorge',
    phone: '0800 111 0 111',
    url: 'https://www.telefonseelsorge.de',
    hours: '24/7',
    free: true,
    languages: ['de'],
    audience:
      'Anonymous support for any worry, by phone, chat or email. Also 0800 111 0 222 or 116 123.',
    sources: [src('https://www.telefonseelsorge.de/', 'TelefonSeelsorge Deutschland')],
  },
  {
    id: 'de-hilfetelefon',
    country: 'DE',
    kind: 'domestic-violence',
    name: 'Hilfetelefon Gewalt gegen Frauen',
    phone: '116 016',
    hours: '24/7',
    free: true,
    audience: 'For women experiencing violence, and people supporting them.',
    sources: [fah('de', 'Germany')],
  },
  {
    id: 'de-nummer-gegen-kummer',
    country: 'DE',
    kind: 'child-helpline',
    name: 'Nummer gegen Kummer',
    phone: '116 111',
    audience: 'For children and young people. Parents can call 0800 111 0 550.',
    sources: [fah('de', 'Germany')],
  },
  {
    id: 'fr-3114',
    country: 'FR',
    kind: 'crisis-line',
    name: '3114 – Numéro national de prévention du suicide',
    phone: '3114',
    url: 'https://3114.fr',
    hours: '24/7',
    free: true,
    languages: ['fr'],
    audience:
      'For people in distress or thinking about suicide, and people worried about someone. Answered by health professionals.',
    sources: [src('https://3114.fr/', '3114, numéro national de prévention du suicide')],
  },
  {
    id: 'fr-sos-amitie',
    country: 'FR',
    kind: 'crisis-line',
    name: 'SOS Amitié',
    phone: '09 72 39 40 50',
    hours: '24/7',
    free: true,
    audience: 'Listening support for any worry, by phone or chat.',
    sources: [fah('fr', 'France')],
  },
  {
    id: 'fr-3919',
    country: 'FR',
    kind: 'domestic-violence',
    name: '3919 – Violences Femmes Info',
    phone: '3919',
    audience: 'Information and guidance for women experiencing violence.',
    sources: [fah('fr', 'France')],
  },
  {
    id: 'es-024',
    country: 'ES',
    kind: 'crisis-line',
    name: 'Línea 024',
    phone: '024',
    url: 'https://www.sanidad.gob.es/linea024/home.htm',
    hours: '24/7',
    free: true,
    languages: ['es'],
    audience:
      'For people with thoughts of suicide, and their families. Chat and sign-language access available.',
    sources: [
      src('https://www.sanidad.gob.es/linea024/home.htm', 'Ministerio de Sanidad: Línea 024'),
    ],
  },
  {
    id: 'es-esperanza',
    country: 'ES',
    kind: 'crisis-line',
    name: 'Teléfono de la Esperanza',
    phone: '717 003 717',
    hours: '24/7',
    free: true,
    audience: 'Emotional crisis support for anxiety, depression or other difficult moments.',
    sources: [fah('es', 'Spain')],
  },
  {
    id: 'es-016',
    country: 'ES',
    kind: 'domestic-violence',
    name: 'Teléfono 016',
    phone: '016',
    audience: 'Information, legal advice and support for all forms of violence against women.',
    sources: [fah('es', 'Spain')],
  },
  {
    id: 'es-anar',
    country: 'ES',
    kind: 'child-helpline',
    name: 'Fundación ANAR',
    phone: '900 20 20 10',
    audience: 'For children and teenagers with any problem.',
    sources: [fah('es', 'Spain')],
  },
  {
    id: 'pt-1411',
    country: 'PT',
    kind: 'crisis-line',
    name: 'Linha de Prevenção do Suicídio e Apoio Psicológico 1411',
    phone: '1411',
    free: true,
    audience: 'Psychological support and suicide prevention.',
    sources: [fah('pt', 'Portugal')],
  },
  {
    id: 'pt-sos-voz-amiga',
    country: 'PT',
    kind: 'crisis-line',
    name: 'SOS Voz Amiga',
    phone: '213 544 545',
    free: true,
    audience: 'Listening support for people in crisis.',
    sources: [fah('pt', 'Portugal')],
  },
  {
    id: 'pt-violencia-domestica',
    country: 'PT',
    kind: 'domestic-violence',
    name: 'Serviço de Informação a Vítimas de Violência Doméstica',
    phone: '800 202 148',
    sms: '3060',
    free: true,
    audience: 'Free, anonymous, confidential support for victims of domestic violence.',
    sources: [fah('pt', 'Portugal')],
  },
  {
    id: 'it-telefono-amico',
    country: 'IT',
    kind: 'crisis-line',
    name: 'Telefono Amico Italia',
    phone: '02 2327 2327',
    free: true,
    audience: 'Listening support for anyone feeling alone or in difficulty.',
    sources: [fah('it', 'Italy')],
  },
  {
    id: 'it-samaritans',
    country: 'IT',
    kind: 'crisis-line',
    name: 'Samaritans Onlus',
    phone: '06 77208977',
    hours: '13:00–22:00 daily',
    free: true,
    audience: 'Emotional support for people in distress.',
    sources: [fah('it', 'Italy')],
  },
  {
    id: 'it-1522',
    country: 'IT',
    kind: 'domestic-violence',
    name: '1522 Antiviolenza e Stalking',
    phone: '1522',
    hours: '24/7',
    free: true,
    audience: 'For anyone facing violence or stalking, by phone or chat.',
    sources: [fah('it', 'Italy')],
  },
  {
    id: 'it-telefono-azzurro',
    country: 'IT',
    kind: 'child-helpline',
    name: 'Telefono Azzurro',
    phone: '19696',
    hours: '24/7',
    free: true,
    audience: 'For children and teenagers.',
    sources: [fah('it', 'Italy')],
  },
  {
    id: 'nl-113',
    country: 'NL',
    kind: 'crisis-line',
    name: '113 Zelfmoordpreventie',
    phone: '113',
    url: 'https://www.113.nl',
    free: true,
    languages: ['nl'],
    audience: 'For people thinking about suicide, by phone or chat.',
    sources: [src('https://www.113.nl/', '113 Zelfmoordpreventie')],
  },
  {
    id: 'pl-116123',
    country: 'PL',
    kind: 'crisis-line',
    name: 'Telefon Zaufania 116 123',
    phone: '116 123',
    hours: '24/7',
    free: true,
    audience: 'Emotional support for adults in crisis.',
    sources: [fah('pl', 'Poland')],
  },
  {
    id: 'pl-centrum-wsparcia',
    country: 'PL',
    kind: 'crisis-line',
    name: 'Centrum Wsparcia',
    phone: '800 70 2222',
    free: true,
    audience: 'Support for adults in emotional crisis.',
    sources: [fah('pl', 'Poland')],
  },
  {
    id: 'pl-niebieska-linia',
    country: 'PL',
    kind: 'domestic-violence',
    name: 'Niebieska Linia',
    phone: '800 120 002',
    free: true,
    audience: 'Free, confidential support for people experiencing domestic violence.',
    sources: [fah('pl', 'Poland')],
  },
  {
    id: 'pl-116111',
    country: 'PL',
    kind: 'child-helpline',
    name: 'Telefon Zaufania dla Dzieci i Młodzieży',
    phone: '116 111',
    free: true,
    audience: 'For children and young people.',
    sources: [fah('pl', 'Poland')],
  },
  {
    id: 'se-mind-90101',
    country: 'SE',
    kind: 'crisis-line',
    name: 'Mind Självmordslinjen',
    phone: '90101',
    hours: '24/7',
    free: true,
    audience: 'For people with thoughts of suicide, by phone or chat.',
    sources: [fah('se', 'Sweden')],
  },
  {
    id: 'se-kvinnofridslinjen',
    country: 'SE',
    kind: 'domestic-violence',
    name: 'Kvinnofridslinjen',
    phone: '116 016',
    free: true,
    audience: 'For women subjected to violence or threats.',
    sources: [fah('se', 'Sweden')],
  },
  {
    id: 'se-bris',
    country: 'SE',
    kind: 'child-helpline',
    name: 'Bris',
    phone: '116 111',
    sms: '116 111',
    free: true,
    audience: 'For children and young people.',
    sources: [fah('se', 'Sweden')],
  },
  {
    id: 'ua-116123',
    country: 'UA',
    kind: 'domestic-violence',
    name: 'National hotline on domestic violence, trafficking and gender discrimination',
    phone: '116 123',
    audience: 'For people facing domestic violence, trafficking or discrimination.',
    sources: [fah('ua', 'Ukraine')],
  },
  {
    id: 'ua-children',
    country: 'UA',
    kind: 'child-helpline',
    name: 'National hotline for children and young people',
    phone: '0 800 500 225',
    audience: 'For children, young people and parents.',
    sources: [fah('ua', 'Ukraine')],
  },

  // ───────────────────────────── North America ─────────────────────────────
  {
    id: 'us-988',
    country: 'US',
    kind: 'crisis-line',
    name: '988 Suicide & Crisis Lifeline',
    phone: '988',
    sms: '988',
    url: 'https://988lifeline.org',
    hours: '24/7',
    free: true,
    audience:
      'Call, text or chat for any mental health, substance use or suicidal crisis. Chat: chat.988lifeline.org.',
    sources: [src('https://988lifeline.org/', '988 Suicide & Crisis Lifeline')],
  },
  {
    id: 'us-crisis-text-line',
    country: 'US',
    kind: 'text-line',
    name: 'Crisis Text Line',
    sms: '741741',
    smsKeyword: 'HOME',
    url: 'https://www.crisistextline.org',
    hours: '24/7',
    free: true,
    audience: 'Text support from a trained volunteer crisis counsellor.',
    sources: [src('https://www.crisistextline.org/', 'Crisis Text Line')],
  },
  {
    id: 'us-ndvh',
    country: 'US',
    kind: 'domestic-violence',
    name: 'National Domestic Violence Hotline',
    phone: '1-800-799-7233',
    sms: '88788',
    smsKeyword: 'START',
    url: 'https://www.thehotline.org',
    hours: '24/7',
    audience: 'For anyone experiencing domestic violence, or worried about someone.',
    sources: [src('https://www.thehotline.org/', 'The National Domestic Violence Hotline')],
  },
  {
    id: 'us-poison-control',
    country: 'US',
    kind: 'poison',
    name: 'Poison Control',
    phone: '1-800-222-1222',
    url: 'https://www.poison.org',
    free: true,
    audience:
      'Expert help if someone may have been poisoned. If they collapse, have a seizure or trouble breathing, call 911.',
    sources: [src('https://www.poison.org/', 'Poison Control (National Capital Poison Center)')],
  },
  {
    id: 'ca-988',
    country: 'CA',
    kind: 'crisis-line',
    name: '9-8-8 Suicide Crisis Helpline',
    phone: '988',
    sms: '988',
    url: 'https://988.ca',
    hours: '24/7',
    languages: ['en', 'fr'],
    audience: 'For anyone thinking about suicide, or worried about someone.',
    sources: [src('https://988.ca/', '9-8-8: Suicide Crisis Helpline')],
  },
  {
    id: 'ca-kids-help-phone',
    country: 'CA',
    kind: 'child-helpline',
    name: 'Kids Help Phone',
    phone: '1-800-668-6868',
    sms: '686868',
    smsKeyword: 'CONNECT',
    url: 'https://kidshelpphone.ca',
    hours: '24/7',
    audience: 'For young people in Canada, by phone, text or chat.',
    sources: [src('https://www.kidshelpphone.ca/', 'Kids Help Phone')],
  },
  {
    id: 'mx-linea-de-la-vida',
    country: 'MX',
    kind: 'crisis-line',
    name: 'Línea de la Vida',
    phone: '800 911 2000',
    hours: '24/7',
    free: true,
    languages: ['es'],
    audience: 'National line for mental health, addiction and suicide prevention (CONASAMA).',
    sources: [
      fah('mx', 'Mexico'),
      src(
        'https://www.gob.mx/conasama/articulos/linea-de-la-vida-800-911-2000',
        'CONASAMA: La Línea de la Vida 800 911 2000',
      ),
    ],
  },
  {
    id: 'mx-saptel',
    country: 'MX',
    kind: 'crisis-line',
    name: 'SAPTEL',
    phone: '55 5259 8121',
    languages: ['es'],
    audience: 'Emotional support and crisis counselling by phone.',
    sources: [fah('mx', 'Mexico')],
  },
  {
    id: 'mx-red-nacional-refugios',
    country: 'MX',
    kind: 'domestic-violence',
    name: 'Red Nacional de Refugios',
    phone: '800 822 4460',
    audience: 'Help and safe shelter for women and children facing violence.',
    sources: [fah('mx', 'Mexico')],
  },

  // ───────────────────────────── Latin America ─────────────────────────────
  {
    id: 'br-cvv',
    country: 'BR',
    kind: 'crisis-line',
    name: 'CVV – Centro de Valorização da Vida',
    phone: '188',
    url: 'https://cvv.org.br',
    hours: '24/7',
    free: true,
    languages: ['pt'],
    audience: 'Emotional support and suicide prevention, by phone, chat or email.',
    sources: [src('https://cvv.org.br/', 'CVV – Centro de Valorização da Vida')],
  },
  {
    id: 'br-ligue-180',
    country: 'BR',
    kind: 'domestic-violence',
    name: 'Ligue 180',
    phone: '180',
    hours: '24/7',
    free: true,
    languages: ['pt'],
    audience: 'Support for women facing violence.',
    sources: [fah('br', 'Brazil')],
  },
  {
    id: 'ar-asistencia-suicida',
    country: 'AR',
    kind: 'crisis-line',
    name: 'Centro de Asistencia al Suicida',
    phone: '0800 345 1435',
    free: true,
    languages: ['es'],
    audience: 'Suicide prevention support from trained volunteers.',
    sources: [fah('ar', 'Argentina')],
  },
  {
    id: 'ar-salud-mental',
    country: 'AR',
    kind: 'mental-health',
    name: 'Línea nacional de salud mental',
    phone: '0800 999 0091',
    free: true,
    audience: 'National guidance and support for mental health crises.',
    sources: [fah('ar', 'Argentina')],
  },
  {
    id: 'ar-144',
    country: 'AR',
    kind: 'domestic-violence',
    name: 'Línea 144',
    phone: '144',
    free: true,
    audience: 'Support for people facing gender-based violence.',
    sources: [fah('ar', 'Argentina')],
  },
  {
    id: 'co-106',
    country: 'CO',
    kind: 'mental-health',
    name: 'Línea 106 Nacional de Salud Mental',
    phone: '106',
    audience: 'Mental health support for everyone.',
    sources: [fah('co', 'Colombia')],
  },
  {
    id: 'co-155',
    country: 'CO',
    kind: 'domestic-violence',
    name: 'Línea 155',
    phone: '155',
    free: true,
    audience: 'Guidance for women facing violence.',
    sources: [fah('co', 'Colombia')],
  },
  {
    id: 'co-141',
    country: 'CO',
    kind: 'child-helpline',
    name: 'Línea 141 ICBF',
    phone: '141',
    hours: '24/7',
    free: true,
    audience: 'For children, young people and parents.',
    sources: [fah('co', 'Colombia')],
  },
  {
    id: 'cl-4141',
    country: 'CL',
    kind: 'crisis-line',
    name: 'Línea *4141',
    phone: '*4141',
    free: true,
    languages: ['es'],
    audience: 'Ministry of Health suicide prevention line.',
    sources: [fah('cl', 'Chile')],
  },
  {
    id: 'cl-1455',
    country: 'CL',
    kind: 'domestic-violence',
    name: 'SernamEG Te Orienta 1455',
    phone: '1455',
    free: true,
    audience: 'Guidance for people facing violence against women, by phone or WhatsApp.',
    sources: [fah('cl', 'Chile')],
  },
  {
    id: 'pe-113',
    country: 'PE',
    kind: 'mental-health',
    name: 'Línea 113 Salud',
    phone: '113',
    free: true,
    audience: 'Ministry of Health guidance line, including mental health support.',
    sources: [fah('pe', 'Peru')],
  },
  {
    id: 'pe-100',
    country: 'PE',
    kind: 'domestic-violence',
    name: 'Línea 100',
    phone: '100',
    hours: '24/7',
    free: true,
    audience: 'For people facing family or sexual violence.',
    sources: [fah('pe', 'Peru')],
  },

  // ───────────────────────────── Oceania ─────────────────────────────
  {
    id: 'au-lifeline',
    country: 'AU',
    kind: 'crisis-line',
    name: 'Lifeline',
    phone: '13 11 14',
    sms: '0477 13 11 14',
    url: 'https://www.lifeline.org.au',
    hours: '24/7',
    audience: 'Crisis support and suicide prevention by phone, text or chat.',
    sources: [src('https://www.lifeline.org.au/', 'Lifeline Australia')],
  },
  {
    id: 'au-1800respect',
    country: 'AU',
    kind: 'domestic-violence',
    name: '1800RESPECT',
    phone: '1800 737 732',
    sms: '0458 737 732',
    url: 'https://www.1800respect.org.au',
    hours: '24/7',
    free: true,
    audience: 'For anyone affected by domestic, family or sexual violence.',
    sources: [src('https://www.1800respect.org.au/', '1800RESPECT')],
  },
  {
    id: 'nz-1737',
    country: 'NZ',
    kind: 'crisis-line',
    name: 'Need to talk? 1737',
    phone: '1737',
    sms: '1737',
    url: 'https://1737.org.nz',
    hours: '24/7',
    free: true,
    audience: 'Call or text to talk with a trained counsellor.',
    sources: [src('https://1737.org.nz/', '1737 Need to talk?')],
  },
];
