/**
 * Semantic icon names mapped to Phosphor icons. Components ask for meaning ("shield",
 * "close"), never for a specific glyph, so the set can be swapped in one place.
 * Server-safe: uses Phosphor's SSR entry (no React context).
 */
import {
  AmbulanceIcon,
  ArrowBendUpLeftIcon,
  ArrowClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  BankIcon,
  BedIcon,
  BellIcon,
  BellRingingIcon,
  BellSlashIcon,
  BinocularsIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CertificateIcon,
  ChartBarIcon,
  ChatCircleTextIcon,
  ChatTextIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  CloudFogIcon,
  CloudIcon,
  CloudLightningIcon,
  CloudMoonIcon,
  CloudRainIcon,
  CloudSnowIcon,
  CloudSunIcon,
  ConfettiIcon,
  CopyIcon,
  CrosshairIcon,
  DesktopIcon,
  DotsThreeIcon,
  DownloadSimpleIcon,
  DropIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FirstAidKitIcon,
  FlagIcon,
  FlowerLotusIcon,
  GearSixIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandHeartIcon,
  HeartbeatIcon,
  HeartIcon,
  InfoIcon,
  LifebuoyIcon,
  LightbulbIcon,
  LightningIcon,
  LinkSimpleIcon,
  ListIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MicrophoneIcon,
  MinusIcon,
  MoonIcon,
  MoonStarsIcon,
  PaperPlaneRightIcon,
  PathIcon,
  PencilSimpleIcon,
  PersonSimpleWalkIcon,
  PhoneIcon,
  PillIcon,
  PlusIcon,
  PrinterIcon,
  QrCodeIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  SignOutIcon,
  SignpostIcon,
  StopIcon,
  SunHorizonIcon,
  SunIcon,
  ThermometerIcon,
  TicketIcon,
  TranslateIcon,
  TrashIcon,
  UmbrellaIcon,
  UserCircleIcon,
  UsersThreeIcon,
  WalletIcon,
  WarningIcon,
  WarningOctagonIcon,
  WindIcon,
  XIcon,
} from '@phosphor-icons/react/ssr';
import type { ComponentType, SVGProps } from 'react';

export type IconWeight = 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
export type IconComponent = ComponentType<
  SVGProps<SVGSVGElement> & { size?: number | string; weight?: IconWeight; mirrored?: boolean }
>;

export const ICONS = {
  // Modules (pictograms, used with weight="fill")
  today: SignpostIcon,
  path: PathIcon,
  shield: ShieldCheckIcon,
  circles: UsersThreeIcon,
  ask: ChatCircleTextIcon,
  signals: BinocularsIcon,
  money: WalletIcon,
  mind: FlowerLotusIcon,
  health: HeartbeatIcon,
  civic: BankIcon,
  surroundings: CloudSunIcon,
  goals: FlagIcon,
  org: BuildingsIcon,
  support: LifebuoyIcon,
  // Actions & UI
  add: PlusIcon,
  back: ArrowLeftIcon,
  forward: ArrowRightIcon,
  external: ArrowSquareOutIcon,
  close: XIcon,
  menu: ListIcon,
  more: DotsThreeIcon,
  check: CheckIcon,
  chevronRight: CaretRightIcon,
  chevronLeft: CaretLeftIcon,
  chevronDown: CaretDownIcon,
  search: MagnifyingGlassIcon,
  edit: PencilSimpleIcon,
  delete: TrashIcon,
  copy: CopyIcon,
  share: ShareNetworkIcon,
  download: DownloadSimpleIcon,
  retry: ArrowClockwiseIcon,
  send: PaperPlaneRightIcon,
  stop: StopIcon,
  settings: GearSixIcon,
  signOut: SignOutIcon,
  account: UserCircleIcon,
  language: TranslateIcon,
  light: SunIcon,
  dark: MoonIcon,
  system: DesktopIcon,
  lock: LockSimpleIcon,
  show: EyeIcon,
  hide: EyeSlashIcon,
  link: LinkSimpleIcon,
  calendar: CalendarBlankIcon,
  time: ClockIcon,
  phone: PhoneIcon,
  text: ChatTextIcon,
  email: EnvelopeSimpleIcon,
  web: GlobeIcon,
  voice: MicrophoneIcon,
  qr: QrCodeIcon,
  certificate: CertificateIcon,
  work: BriefcaseIcon,
  learn: GraduationCapIcon,
  care: HandHeartIcon,
  quick: LightningIcon,
  flag: FlagIcon,
  air: WindIcon,
  reply: ArrowBendUpLeftIcon,
  bell: BellIcon,
  bellOff: BellSlashIcon,
  minus: MinusIcon,
  print: PrinterIcon,
  team: UsersThreeIcon,
  chart: ChartBarIcon,
  ticket: TicketIcon,
  // Health
  sleep: BedIcon,
  move: PersonSimpleWalkIcon,
  water: DropIcon,
  medicine: PillIcon,
  firstAid: FirstAidKitIcon,
  ambulance: AmbulanceIcon,
  reminder: BellRingingIcon,
  // Surroundings
  place: MapPinIcon,
  locate: CrosshairIcon,
  thermometer: ThermometerIcon,
  umbrella: UmbrellaIcon,
  sunrise: SunHorizonIcon,
  wxClear: SunIcon,
  wxClearNight: MoonStarsIcon,
  wxPartly: CloudSunIcon,
  wxPartlyNight: CloudMoonIcon,
  wxCloudy: CloudIcon,
  wxFog: CloudFogIcon,
  wxRain: CloudRainIcon,
  wxSnow: CloudSnowIcon,
  wxStorm: CloudLightningIcon,
  // Reactions (Circles)
  heart: HeartIcon,
  idea: LightbulbIcon,
  celebrate: ConfettiIcon,
  // Status
  info: InfoIcon,
  caution: WarningIcon,
  danger: WarningOctagonIcon,
  safe: CheckCircleIcon,
} satisfies Record<string, IconComponent>;

export type IconName = keyof typeof ICONS;
