/**
 * Generates tokens.css from src/index.ts. Run: pnpm --filter @waypoint/tokens build
 * The output is committed so the web app works without a build step.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  type ColorRoles,
  dark,
  fontFamily,
  fontSize,
  fontWeight,
  layout,
  light,
  lineHeight,
  MODULE_LINES,
  type ModuleLine,
  moduleLine,
  moduleTint,
  motion,
  radius,
  SERIES_HUES,
  series,
  shadow,
  space,
  toCss,
  zIndex,
} from '../src/index';

const kebab = (s: string) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

function colorVars(roles: ColorRoles, mode: 'light' | 'dark'): string[] {
  const lines = Object.entries(roles).map(([k, v]) => `--wp-${kebab(k)}: ${toCss(v)};`);
  for (const m of Object.keys(MODULE_LINES) as ModuleLine[]) {
    lines.push(`--wp-line-${m}: ${toCss(moduleLine(m, mode))};`);
    lines.push(`--wp-tint-${m}: ${toCss(moduleTint(m, mode))};`);
  }
  SERIES_HUES.forEach((_, i) => {
    lines.push(`--wp-series-${i + 1}: ${toCss(series(i, mode))};`);
  });
  lines.push(`--wp-shadow-raised: ${mode === 'light' ? shadow.raised : shadow.darkEdge};`);
  lines.push(
    `--wp-shadow-overlay: ${mode === 'light' ? shadow.overlay : `${shadow.darkEdge}, 0 16px 40px rgb(0 0 0 / 0.35)`};`,
  );
  return lines;
}

const staticVars: string[] = [
  `--wp-font-sans: ${fontFamily.sans};`,
  `--wp-font-system: ${fontFamily.system};`,
  ...Object.entries(fontSize).map(([k, v]) => `--wp-text-${k}: ${v}rem;`),
  ...Object.entries(fontWeight).map(([k, v]) => `--wp-weight-${k}: ${v};`),
  ...Object.entries(lineHeight).map(([k, v]) => `--wp-leading-${k}: ${v};`),
  ...Object.entries(space).map(([k, v]) => `--wp-space-${k}: ${v / 16}rem;`),
  ...Object.entries(radius).map(
    ([k, v]) => `--wp-radius-${k}: ${k === 'round' ? '999px' : `${v / 16}rem`};`,
  ),
  `--wp-duration-instant: ${motion.instant}ms;`,
  `--wp-duration-fast: ${motion.fast}ms;`,
  `--wp-duration-base: ${motion.base}ms;`,
  `--wp-duration-slow: ${motion.slow}ms;`,
  `--wp-duration-flip: ${motion.flip}ms;`,
  `--wp-ease-out: ${motion.easeOut};`,
  `--wp-ease-in: ${motion.easeIn};`,
  `--wp-ease-standard: ${motion.easeStandard};`,
  ...Object.entries(zIndex).map(([k, v]) => `--wp-z-${k}: ${v};`),
  ...Object.entries(layout).map(([k, v]) => `--wp-${kebab(k)}: ${v}rem;`),
];

const indent = (lines: string[], n: number) => lines.map((l) => `${' '.repeat(n)}${l}`).join('\n');

const css = `/* Generated by packages/tokens/scripts/build-css.ts — do not edit by hand. */
@layer tokens {
  :root {
    color-scheme: light;
${indent([...staticVars, ...colorVars(light, 'light')], 4)}
  }

  :root[data-theme='dark'] {
    color-scheme: dark;
${indent(colorVars(dark, 'dark'), 4)}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme='light']) {
      color-scheme: dark;
${indent(colorVars(dark, 'dark'), 6)}
    }
  }
}
`;

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'tokens.css');
writeFileSync(out, css);
console.log(`Wrote ${out}`);
