apiVersion: v1
kind: Namespace
metadata:
  name: waypoint
  labels:
    # Pods here may not run as root, gain privileges or use the host's resources.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
