/**
 * Writes src/country-names.ts: the name of every country Waypoint has help lines for, in each
 * of the app's languages. Hermes has no Intl.DisplayNames, and its polyfill would add about a
 * megabyte of data for 48 names, so the names are taken from Node's Unicode data here instead.
 * test/country-names.test.ts fails when the list of countries changes and this needs running.
 *
 *   pnpm --filter @waypoint/mobile country-names
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { COUNTRIES } from '@waypoint/content';
import { locales } from '@waypoint/i18n';

export function countryNames(): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {};
  for (const c of COUNTRIES) {
    out[c.code] = Object.fromEntries(
      locales.map((l) => [l, new Intl.DisplayNames([l], { type: 'region' }).of(c.code) ?? c.name]),
    );
  }
  return out;
}

if (process.argv[1]?.endsWith('country-names.ts')) {
  const names = countryNames();
  const body = Object.entries(names)
    .map(
      ([code, byLocale]) =>
        `  ${code}: { ${Object.entries(byLocale)
          .map(([l, n]) => `${l}: ${JSON.stringify(n)}`)
          .join(', ')} },`,
    )
    .join('\n');
  const file = `// Generated by scripts/country-names.ts from the Unicode CLDR data in Node.js. Do not edit.
import type { Locale } from '@waypoint/i18n';

export const COUNTRY_NAMES: Record<string, Record<Locale, string>> = {
${body}
};
`;
  writeFileSync(join(import.meta.dirname, '../src/country-names.ts'), file);
  console.log(`Wrote ${Object.keys(names).length} countries.`);
}
