#!/usr/bin/env node
/**
 * Writes src/ui/icon-paths.ts: the path data of the few Phosphor icons the app uses, in the
 * two weights it uses. The web app uses the same icons (packages/ui/src/icons.ts) under the
 * same names. Shipping only these keeps the bundle small (phosphor-react-native has 1,500
 * icons in six weights).
 *
 *   node scripts/icons.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// The package doesn't export its package.json, so find it through node_modules.
const pkgDir = join(here, '../node_modules/phosphor-react-native');
const { version } = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'));

/** Waypoint's name for each icon → Phosphor's. Keep in step with packages/ui/src/icons.ts. */
const ICONS = {
  // Modules
  today: 'Signpost',
  path: 'Path',
  shield: 'ShieldCheck',
  circles: 'UsersThree',
  ask: 'ChatCircleText',
  signals: 'Binoculars',
  money: 'Wallet',
  mind: 'FlowerLotus',
  health: 'Heartbeat',
  civic: 'Bank',
  surroundings: 'CloudSun',
  goals: 'Flag',
  org: 'Buildings',
  support: 'Lifebuoy',
  // Actions and interface
  add: 'Plus',
  back: 'ArrowLeft',
  forward: 'ArrowRight',
  external: 'ArrowSquareOut',
  close: 'X',
  more: 'DotsThree',
  check: 'Check',
  chevronRight: 'CaretRight',
  chevronLeft: 'CaretLeft',
  chevronDown: 'CaretDown',
  copy: 'Copy',
  paste: 'ClipboardText',
  share: 'ShareNetwork',
  retry: 'ArrowClockwise',
  send: 'PaperPlaneRight',
  stop: 'Stop',
  settings: 'GearSix',
  signOut: 'SignOut',
  account: 'UserCircle',
  language: 'Translate',
  light: 'Sun',
  dark: 'Moon',
  system: 'DeviceMobile',
  lock: 'LockSimple',
  phone: 'Phone',
  text: 'ChatText',
  email: 'EnvelopeSimple',
  web: 'Globe',
  care: 'HandHeart',
  flag: 'Flag',
  place: 'MapPin',
  time: 'Clock',
  history: 'ClockCounterClockwise',
  search: 'MagnifyingGlass',
  delete: 'Trash',
  offline: 'CloudSlash',
  // Status
  info: 'Info',
  caution: 'Warning',
  danger: 'WarningOctagon',
  safe: 'CheckCircle',
};

const WEIGHTS = ['regular', 'fill'];

function pathsFor(phosphorName) {
  const src = readFileSync(join(pkgDir, 'src/defs', `${phosphorName}.tsx`), 'utf8');
  const out = {};
  for (const weight of WEIGHTS) {
    const block = new RegExp(`\\[\\s*'${weight}',\\s*<>([\\s\\S]*?)</>`).exec(src);
    if (!block) throw new Error(`${phosphorName}: no ${weight} weight`);
    const body = block[1];
    const elements = [...body.matchAll(/<(\w+)/g)].map((m) => m[1]);
    if (elements.some((e) => e !== 'Path'))
      throw new Error(
        `${phosphorName} (${weight}) uses ${elements.join(', ')}; only paths are supported`,
      );
    out[weight] = [...body.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]).join(' ');
  }
  return out;
}

const lines = Object.entries(ICONS).map(([name, phosphor]) => {
  const p = pathsFor(phosphor);
  return `  ${name}: {\n    regular: '${p.regular}',\n    fill: '${p.fill}',\n  },`;
});

const file = `// Generated by scripts/icons.mjs from phosphor-react-native ${version}
// (MIT License, Phosphor Icons — https://phosphoricons.com). Do not edit by hand.

export const ICON_PATHS = {
${lines.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(join(here, '../src/ui/icon-paths.ts'), file);
console.log(`Wrote ${Object.keys(ICONS).length} icons.`);
