#!/usr/bin/env node
/**
 * Set (or remove) message keys in all seven language files at once, so no language is ever
 * left behind.
 *
 *   node scripts/i18n-set.mjs changes.json
 *
 * changes.json maps a dotted key to its text in every language, or to null to remove it:
 *
 *   {
 *     "forecasts.empty": { "en": "…", "hi": "…", "es": "…", "fr": "…", "pt": "…", "ar": "…", "sw": "…" },
 *     "auth.oldKey": null
 *   }
 *
 * A key missing a language is refused. Files are written exactly as the app expects them
 * (two-space JSON with a final newline), and packages/i18n/messages/en.d.json.ts — the typed
 * copy the phone app's type checks read — is rewritten to match, as the web build would.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const LOCALES = ['en', 'hi', 'es', 'fr', 'pt', 'ar', 'sw'];
const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'packages', 'i18n', 'messages');

const input = process.argv[2];
if (!input) {
  console.error('Usage: node scripts/i18n-set.mjs changes.json');
  process.exit(1);
}
const changes = JSON.parse(readFileSync(input, 'utf8'));

for (const [key, value] of Object.entries(changes)) {
  if (value === null) continue;
  const missing = LOCALES.filter((l) => typeof value?.[l] !== 'string' || !value[l].trim());
  if (missing.length) {
    console.error(`${key}: missing ${missing.join(', ')}`);
    process.exit(1);
  }
}

for (const locale of LOCALES) {
  const file = join(dir, `${locale}.json`);
  const messages = JSON.parse(readFileSync(file, 'utf8'));
  for (const [key, value] of Object.entries(changes)) {
    const path = key.split('.');
    const leaf = path.pop();
    let node = messages;
    for (const part of path) {
      if (value === null && (typeof node[part] !== 'object' || node[part] === null)) {
        node = null;
        break;
      }
      if (typeof node[part] !== 'object' || node[part] === null) node[part] = {};
      node = node[part];
    }
    if (!node) continue;
    if (value === null) delete node[leaf];
    else node[leaf] = value[locale];
  }
  const json = JSON.stringify(messages, null, 2);
  writeFileSync(file, `${json}\n`);
  // The typed copy of the English messages, exactly as the web build writes it: the phone
  // app's type checks read it, so it must never lag behind en.json.
  if (locale === 'en')
    writeFileSync(
      join(dir, 'en.d.json.ts'),
      `// This file is auto-generated by next-intl, do not edit directly.\n// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments\n\ndeclare const messages: ${json};\nexport default messages;`,
    );
}
console.log(`Updated ${Object.keys(changes).length} key(s) in ${LOCALES.length} languages.`);
